-- CreateTable
CREATE TABLE "Product" (
    "id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "titleKey" TEXT,
    "titleEn" TEXT,
    "titleLv" TEXT,
    "description" TEXT,
    "brand" TEXT NOT NULL,
    "price" DOUBLE PRECISION NOT NULL,
    "oldPrice" DOUBLE PRECISION,
    "rating" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "ratingCount" INTEGER NOT NULL DEFAULT 0,
    "reviewCount" INTEGER NOT NULL DEFAULT 0,
    "image" TEXT,
    "images" TEXT[],
    "metaTitle" TEXT,
    "metaDescription" TEXT,
    "ogImage" TEXT,
    "ogAlt" TEXT,
    "badges" TEXT[],
    "category" TEXT NOT NULL,
    "stock" INTEGER NOT NULL DEFAULT 0,
    "barcode" TEXT,
    "purpose" TEXT,
    "purposeEn" TEXT,
    "purposeLv" TEXT,
    "relatedProductIds" TEXT[],
    "oftenBoughtTogether" TEXT[],
    "minOrderQuantities" JSONB,
    "technicalSpecs" JSONB,
    "bulkPricingTiers" JSONB,
    "demoVideo" JSONB,
    "distributorName" JSONB,
    "distributorAddress" JSONB,
    "sku" TEXT,
    "unitOfMeasure" TEXT,
    "certificates" TEXT[],
    "packagingSize" INTEGER,
    "compatibleEquipment" TEXT[],
    "manufacturerName" TEXT,
    "manufacturerAddress" TEXT,
    "manufacturerEmail" TEXT,
    "distributorEmail" TEXT,
    "bonusRate" DOUBLE PRECISION,
    "feature1" TEXT,
    "feature1En" TEXT,
    "feature1Lv" TEXT,
    "feature2" TEXT,
    "feature2En" TEXT,
    "feature2Lv" TEXT,
    "feature3" TEXT,
    "feature3En" TEXT,
    "feature3Lv" TEXT,
    "feature4" TEXT,
    "feature4En" TEXT,
    "feature4Lv" TEXT,
    "specVolume" TEXT,
    "specType" TEXT,
    "specCountry" TEXT,
    "isDeleted" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Product_pkey" PRIMARY KEY ("id")
);
