import { privacyContent } from '@/data/privacy-content'
import { termsContent } from '@/data/terms-content'
import { cookieContent } from '@/data/cookie-content'
import { returnPolicyContent } from '@/data/return-policy-content'
import { COMPANY } from '@/data/company'
import { stores } from '@/data/stores'

// Curated registry of admin-editable site content. Each text entry names a
// translation key already rendered through t(); each image entry names a base
// src already passed through resolveImageSrc(). The /admin/content page renders
// this registry so admins can edit content without knowing keys or paths.
// When new t()-wired content is added to the site, add it here too —
// lib/content-registry.test.ts validates every key and file path.

type ContentDefaults = Record<'ru' | 'en' | 'lv', string>

const storeAddressDefaults = (id: string): ContentDefaults => {
  const store = stores.find((item) => item.id === id)
  return store
    ? { ru: store.address.ru, en: store.address.en, lv: store.address.lv }
    : { ru: '', en: '', lv: '' }
}

export type ContentEntry =
  | { type: 'text'; key: string; label: string; multiline?: boolean; defaults?: ContentDefaults }
  | { type: 'image'; src: string; label: string }

export type ContentSection = {
  id: string
  title: string
  entries: ContentEntry[]
}

export const CONTENT_REGISTRY: ContentSection[] = [
  {
    id: 'home-hero',
    title: 'Главная — Hero',
    entries: [
      { type: 'text', key: 'hero.title', label: 'Заголовок' },
      { type: 'text', key: 'hero.subtitle', label: 'Подзаголовок' },
      { type: 'text', key: 'hero.cta', label: 'Кнопка' },
      { type: 'text', key: 'meta.homeTitle', label: 'SEO — заголовок главной' },
      { type: 'text', key: 'meta.homeDescription', label: 'SEO — описание главной', multiline: true },
      { type: 'text', key: 'hero.alt', label: 'Alt-текст фоновой картинки' },
      { type: 'image', src: '/hero.jpg', label: 'Фоновая картинка' },
    ],
  },
  {
    id: 'home-benefits',
    title: 'Главная — Преимущества',
    entries: [
      { type: 'text', key: 'benefits.deliveryFree', label: 'Бесплатная доставка' },
      { type: 'text', key: 'benefits.consultationMain', label: 'Консультации' },
      { type: 'text', key: 'benefits.processingFast', label: 'Быстрая обработка' },
      { type: 'text', key: 'benefits.inStock', label: 'Товары на складе' },
      { type: 'text', key: 'benefits.brands100', label: 'Оригинальные бренды' },
      { type: 'text', key: 'benefits.bonusPoints', label: 'Бонусные баллы' },
      { type: 'image', src: '/icons/delivery.svg', label: 'Иконка «Доставка»' },
      { type: 'image', src: '/icons/consulting.svg', label: 'Иконка «Консультации»' },
      { type: 'image', src: '/icons/orders.svg', label: 'Иконка «Обработка заказов»' },
      { type: 'image', src: '/icons/goods.svg', label: 'Иконка «Товары на складе»' },
      { type: 'image', src: '/icons/originals.svg', label: 'Иконка «Оригинальные бренды»' },
      { type: 'image', src: '/icons/bonuses.svg', label: 'Иконка «Бонусы»' },
    ],
  },
  {
    id: 'home-showcase',
    title: 'Главная — Витрина и промо-блоки',
    entries: [
      { type: 'text', key: 'products.bestSellers', label: 'Заголовок бестселлеров' },
      { type: 'text', key: 'categories.title', label: 'Заголовок категорий' },
      { type: 'text', key: 'brands.popular', label: 'Заголовок популярных брендов' },
      { type: 'text', key: 'brands.alphabeticalTitle', label: 'Заголовок списка брендов' },
      { type: 'text', key: 'sale.title', label: 'Распродажа — заголовок' },
      { type: 'text', key: 'sale.subtitle', label: 'Распродажа — подзаголовок', multiline: true },
      { type: 'text', key: 'sale.allProducts', label: 'Распродажа — ссылка на все товары' },
      { type: 'text', key: 'home.retailBanner.eyebrow', label: 'Розничный баннер — надзаголовок' },
      { type: 'text', key: 'home.retailBanner.retailOnly', label: 'Розничный баннер — текст', multiline: true },
      { type: 'text', key: 'home.retailBanner.button', label: 'Розничный баннер — кнопка' },
      { type: 'text', key: 'home.productRequest.title', label: 'Запрос товара — заголовок' },
      { type: 'text', key: 'home.productRequest.titleAccent', label: 'Запрос товара — акцент' },
      { type: 'text', key: 'home.productRequest.open', label: 'Запрос товара — кнопка открытия' },
      { type: 'text', key: 'home.productRequest.product', label: 'Запрос товара — поле товара' },
      { type: 'text', key: 'home.productRequest.productPlaceholder', label: 'Запрос товара — подсказка товара' },
      { type: 'text', key: 'home.productRequest.phone', label: 'Запрос товара — поле телефона' },
      { type: 'text', key: 'home.productRequest.phonePlaceholder', label: 'Запрос товара — подсказка телефона' },
      { type: 'text', key: 'home.productRequest.comment', label: 'Запрос товара — поле комментария' },
      { type: 'text', key: 'home.productRequest.commentPlaceholder', label: 'Запрос товара — подсказка комментария' },
      { type: 'text', key: 'home.productRequest.note', label: 'Запрос товара — примечание', multiline: true },
      { type: 'text', key: 'home.productRequest.send', label: 'Запрос товара — отправка' },
      { type: 'text', key: 'home.productRequest.success', label: 'Запрос товара — успешная отправка', multiline: true },
    ],
  },
  {
    id: 'home-bonus',
    title: 'Главная — Бонусная программа',
    entries: [
      { type: 'text', key: 'bonus.section.title', label: 'Заголовок' },
      { type: 'text', key: 'bonus.section.subtitle', label: 'Подзаголовок', multiline: true },
      { type: 'text', key: 'bonus.section.step.earn.title', label: 'Начисление — заголовок' },
      { type: 'text', key: 'bonus.section.step.earn.desc', label: 'Начисление — описание', multiline: true },
      { type: 'text', key: 'bonus.section.step.spend.title', label: 'Использование — заголовок' },
      { type: 'text', key: 'bonus.section.step.spend.desc', label: 'Использование — описание', multiline: true },
      { type: 'text', key: 'bonus.section.step.grow.title', label: 'Рост — заголовок' },
      { type: 'text', key: 'bonus.section.step.grow.desc', label: 'Рост — описание', multiline: true },
    ],
  },
  {
    id: 'about',
    title: 'О нас',
    entries: [
      { type: 'text', key: 'about.title', label: 'Заголовок страницы' },
      { type: 'text', key: 'about.welcome.title', label: 'Приветствие — заголовок' },
      { type: 'text', key: 'about.welcome.p1', label: 'Приветствие — абзац 1', multiline: true },
      { type: 'text', key: 'about.welcome.p2', label: 'Приветствие — абзац 2', multiline: true },
      { type: 'text', key: 'about.welcome.p3', label: 'Приветствие — абзац 3', multiline: true },
      { type: 'text', key: 'about.storesInfo', label: 'Текст о магазинах', multiline: true },
      { type: 'text', key: 'about.storesButton', label: 'Кнопка «Магазины»' },
      { type: 'text', key: 'about.why.title', label: 'Почему мы — заголовок' },
      { type: 'text', key: 'about.why.item1', label: 'Почему мы — пункт 1' },
      { type: 'text', key: 'about.why.item2', label: 'Почему мы — пункт 2' },
      { type: 'text', key: 'about.why.item3', label: 'Почему мы — пункт 3' },
      { type: 'text', key: 'about.why.item4', label: 'Почему мы — пункт 4' },
      { type: 'text', key: 'about.why.item5', label: 'Почему мы — пункт 5' },
    ],
  },
  {
    id: 'faq',
    title: 'FAQ',
    entries: [
      { type: 'text', key: 'faq.site.title', label: 'Заголовок блока' },
      { type: 'text', key: 'faq.site.subtitle', label: 'Подзаголовок блока' },
      // Нумерация с пропусками (нет q3/q9) — ровно как в components/FAQSection.tsx
      { type: 'text', key: 'faq.site.q1', label: 'Вопрос 1' },
      { type: 'text', key: 'faq.site.a1', label: 'Ответ 1', multiline: true },
      { type: 'text', key: 'faq.site.q2', label: 'Вопрос 2' },
      { type: 'text', key: 'faq.site.a2', label: 'Ответ 2', multiline: true },
      { type: 'text', key: 'faq.site.q4', label: 'Вопрос 4' },
      { type: 'text', key: 'faq.site.a4', label: 'Ответ 4', multiline: true },
      { type: 'text', key: 'faq.site.q5', label: 'Вопрос 5' },
      { type: 'text', key: 'faq.site.a5', label: 'Ответ 5', multiline: true },
      { type: 'text', key: 'faq.site.q6', label: 'Вопрос 6' },
      { type: 'text', key: 'faq.site.a6', label: 'Ответ 6', multiline: true },
      { type: 'text', key: 'faq.site.q7', label: 'Вопрос 7' },
      { type: 'text', key: 'faq.site.a7', label: 'Ответ 7', multiline: true },
      { type: 'text', key: 'faq.site.q8', label: 'Вопрос 8' },
      { type: 'text', key: 'faq.site.a8', label: 'Ответ 8', multiline: true },
      { type: 'text', key: 'faq.site.q10', label: 'Вопрос 10' },
      { type: 'text', key: 'faq.site.a10', label: 'Ответ 10', multiline: true },
      { type: 'text', key: 'faq.site.q11', label: 'Вопрос 11' },
      { type: 'text', key: 'faq.site.a11', label: 'Ответ 11', multiline: true },
      { type: 'text', key: 'faq.site.q12', label: 'Вопрос 12' },
      { type: 'text', key: 'faq.site.a12', label: 'Ответ 12', multiline: true },
    ],
  },
  {
    id: 'newsletter',
    title: 'Рассылка',
    entries: [
      { type: 'text', key: 'newsletter.title', label: 'Заголовок' },
      { type: 'text', key: 'newsletter.subtitle', label: 'Подзаголовок' },
      { type: 'text', key: 'newsletter.placeholder', label: 'Плейсхолдер поля email' },
      { type: 'text', key: 'newsletter.subscribe', label: 'Кнопка подписки' },
      { type: 'text', key: 'newsletter.consentPrefix', label: 'Текст согласия' },
      { type: 'text', key: 'newsletter.consentLinkLabel', label: 'Ссылка в согласии' },
    ],
  },
  {
    id: 'footer',
    title: 'Футер',
    entries: [
      { type: 'text', key: 'footer.about', label: 'О компании', multiline: true },
      { type: 'text', key: 'footer.contact', label: 'Заголовок «Контакты»' },
      { type: 'text', key: 'footer.privacy', label: 'Политика конфиденциальности' },
      { type: 'text', key: 'footer.terms', label: 'Условия использования' },
      { type: 'text', key: 'footer.allRightsReserved', label: 'Копирайт (текст после года)' },
      { type: 'text', key: 'footer.cookies', label: 'Ссылка на политику cookie' },
      { type: 'text', key: 'footer.cookieSettings', label: 'Кнопка настроек cookie' },
      { type: 'text', key: 'footer.instagramUrl', label: 'Ссылка Instagram', defaults: { ru: 'https://instagram.com/', en: 'https://instagram.com/', lv: 'https://instagram.com/' } },
      { type: 'text', key: 'footer.facebookUrl', label: 'Ссылка Facebook', defaults: { ru: 'https://facebook.com/', en: 'https://facebook.com/', lv: 'https://facebook.com/' } },
      { type: 'text', key: 'footer.youtubeUrl', label: 'Ссылка YouTube', defaults: { ru: 'https://youtube.com/', en: 'https://youtube.com/', lv: 'https://youtube.com/' } },
    ],
  },
  {
    id: 'contact',
    title: 'Контакты',
    entries: [
      { type: 'text', key: 'contact.title', label: 'Заголовок страницы' },
      { type: 'text', key: 'contact.info', label: 'Заголовок контактных данных' },
      { type: 'text', key: 'contact.formTitle', label: 'Заголовок формы' },
      { type: 'text', key: 'contact.name', label: 'Поле «Имя» — подпись' },
      { type: 'text', key: 'contact.email', label: 'Поле «Email» — подпись' },
      { type: 'text', key: 'contact.subject', label: 'Поле «Тема» — подпись' },
      { type: 'text', key: 'contact.subjectPlaceholder', label: 'Поле «Тема» — подсказка' },
      { type: 'text', key: 'contact.message', label: 'Поле «Сообщение» — подпись' },
      { type: 'text', key: 'contact.send', label: 'Кнопка отправки' },
      { type: 'text', key: 'contact.sending', label: 'Кнопка во время отправки' },
      { type: 'text', key: 'contact.success', label: 'Сообщение после успешной отправки', multiline: true },
      { type: 'text', key: 'contact.errorGeneric', label: 'Сообщение при общей ошибке', multiline: true },
      { type: 'text', key: 'contact.errorRateLimited', label: 'Сообщение при слишком частых отправках', multiline: true },
      { type: 'text', key: 'contact.errorSpam', label: 'Сообщение при срабатывании защиты от спама', multiline: true },
      { type: 'text', key: 'contact.errorCaptcha', label: 'Сообщение при ошибке проверки CAPTCHA', multiline: true },
      { type: 'text', key: 'company.legalAddress', label: 'Юридический адрес', defaults: { ru: COMPANY.legalAddress, en: COMPANY.legalAddress, lv: COMPANY.legalAddress } },
      { type: 'text', key: 'company.officeAddress', label: 'Адрес офиса', defaults: { ru: COMPANY.officeAddress, en: COMPANY.officeAddress, lv: COMPANY.officeAddress } },
      { type: 'text', key: 'company.regNumber', label: 'Регистрационный номер', defaults: { ru: COMPANY.regNumber, en: COMPANY.regNumber, lv: COMPANY.regNumber } },
      { type: 'text', key: 'company.vatNumber', label: 'Номер НДС', defaults: { ru: COMPANY.vatNumber, en: COMPANY.vatNumber, lv: COMPANY.vatNumber } },
      { type: 'text', key: 'company.bankName', label: 'Банк', defaults: { ru: COMPANY.bankName, en: COMPANY.bankName, lv: COMPANY.bankName } },
      { type: 'text', key: 'company.bankAccount', label: 'Банковский счёт', defaults: { ru: COMPANY.bankAccount, en: COMPANY.bankAccount, lv: COMPANY.bankAccount } },
      { type: 'text', key: 'company.swift', label: 'SWIFT', defaults: { ru: COMPANY.swift, en: COMPANY.swift, lv: COMPANY.swift } },
      { type: 'text', key: 'company.phone', label: 'Телефон', defaults: { ru: COMPANY.phone, en: COMPANY.phone, lv: COMPANY.phone } },
      { type: 'text', key: 'company.email', label: 'Email', defaults: { ru: COMPANY.email, en: COMPANY.email, lv: COMPANY.email } },
      { type: 'text', key: 'contact.faq.q1', label: 'FAQ — вопрос 1' },
      { type: 'text', key: 'contact.faq.a1', label: 'FAQ — ответ 1', multiline: true },
      { type: 'text', key: 'contact.faq.q2', label: 'FAQ — вопрос 2' },
      { type: 'text', key: 'contact.faq.a2', label: 'FAQ — ответ 2', multiline: true },
      { type: 'text', key: 'contact.faq.q3', label: 'FAQ — вопрос 3' },
      { type: 'text', key: 'contact.faq.a3', label: 'FAQ — ответ 3', multiline: true },
    ],
  },
  {
    id: 'delivery',
    title: 'Доставка',
    entries: [
      { type: 'text', key: 'deliveryPayment.methods.title', label: 'Заголовок «Способы доставки»' },
      { type: 'text', key: 'deliveryPayment.methods.courierLatvia.label', label: 'Курьер по Латвии — заголовок' },
      { type: 'text', key: 'deliveryPayment.methods.courierLatvia.price', label: 'Курьер по Латвии — цена' },
      { type: 'text', key: 'deliveryPayment.methods.courierLatvia.freeNote', label: 'Курьер по Латвии — условие бесплатной доставки', multiline: true },
      { type: 'text', key: 'deliveryPayment.methods.omniva.label', label: 'OMNIVA — заголовок' },
      { type: 'text', key: 'deliveryPayment.methods.omniva.price', label: 'OMNIVA — цена' },
      { type: 'text', key: 'deliveryPayment.methods.omniva.maxSize', label: 'OMNIVA — макс. размер' },
      { type: 'text', key: 'deliveryPayment.methods.omniva.weight', label: 'OMNIVA — макс. вес' },
      { type: 'text', key: 'deliveryPayment.methods.pickup.label', label: 'Самовывоз — заголовок' },
      { type: 'text', key: 'deliveryPayment.methods.pickup.intro', label: 'Самовывоз — вводный текст', multiline: true },
      { type: 'text', key: 'deliveryPayment.rules.title', label: 'Заголовок «Правила курьерской доставки»' },
      { type: 'text', key: 'deliveryPayment.rules.item1', label: 'Правило 1', multiline: true },
      { type: 'text', key: 'deliveryPayment.rules.item2', label: 'Правило 2', multiline: true },
      { type: 'text', key: 'deliveryPayment.rules.item3', label: 'Правило 3', multiline: true },
      { type: 'text', key: 'deliveryPayment.rules.item4', label: 'Правило 4', multiline: true },
      { type: 'text', key: 'deliveryPayment.rules.item5', label: 'Правило 5', multiline: true },
      { type: 'text', key: 'deliveryPayment.rules.item6', label: 'Правило 6', multiline: true },
      { type: 'text', key: 'deliveryPayment.rules.item7', label: 'Правило 7', multiline: true },
      { type: 'text', key: 'deliveryPayment.rules.item8', label: 'Правило 8', multiline: true },
      { type: 'text', key: 'deliveryPayment.rules.item9', label: 'Правило 9', multiline: true },
      { type: 'text', key: 'deliveryPayment.rules.item10', label: 'Правило 10' },
      { type: 'text', key: 'deliveryPayment.return.title', label: 'Заголовок «Возврат товара»' },
      { type: 'text', key: 'deliveryPayment.return.intro', label: 'Возврат — вводный текст', multiline: true },
      { type: 'text', key: 'deliveryPayment.return.conditionsTitle', label: 'Возврат — заголовок условий' },
      { type: 'text', key: 'deliveryPayment.return.condition1', label: 'Условие возврата 1' },
      { type: 'text', key: 'deliveryPayment.return.condition2', label: 'Условие возврата 2' },
      { type: 'text', key: 'deliveryPayment.return.condition3', label: 'Условие возврата 3' },
      { type: 'text', key: 'deliveryPayment.return.refundNote', label: 'Возврат — про возврат средств', multiline: true },
      { type: 'text', key: 'deliveryPayment.return.exceptionIntro', label: 'Возврат — исключения, вводный текст', multiline: true },
      { type: 'text', key: 'deliveryPayment.return.exceptionItem1', label: 'Возврат — исключение 1', multiline: true },
      { type: 'text', key: 'deliveryPayment.contacts.title', label: 'Заголовок «Вопросы по доставке»' },
      { type: 'text', key: 'deliveryPayment.contacts.intro', label: 'Вопросы по доставке — вводный текст' },
    ],
  },
  {
    id: 'payment',
    title: 'Оплата',
    entries: [
      { type: 'text', key: 'deliveryPayment.payment.methods.title', label: 'Заголовок «Способы оплаты»' },
      { type: 'text', key: 'deliveryPayment.payment.card.label', label: 'Оплата картой — заголовок' },
      { type: 'text', key: 'deliveryPayment.payment.card.note', label: 'Оплата картой — пояснение', multiline: true },
      { type: 'text', key: 'deliveryPayment.payment.cash.label', label: 'Оплата наличными — заголовок' },
      { type: 'text', key: 'deliveryPayment.payment.cash.note', label: 'Оплата наличными — пояснение', multiline: true },
      { type: 'text', key: 'deliveryPayment.payment.transfer.label', label: 'Банковский перевод — заголовок' },
      { type: 'text', key: 'deliveryPayment.payment.transfer.note1', label: 'Банковский перевод — пояснение 1', multiline: true },
      { type: 'text', key: 'deliveryPayment.payment.transfer.note2', label: 'Банковский перевод — пояснение 2', multiline: true },
      { type: 'text', key: 'deliveryPayment.payment.transfer.requisitesTitle', label: 'Заголовок «Реквизиты для оплаты»' },
      { type: 'text', key: 'deliveryPayment.payment.how.title', label: 'Заголовок «Как происходит оплата»' },
      { type: 'text', key: 'deliveryPayment.payment.how.step1', label: 'Шаг оплаты 1' },
      { type: 'text', key: 'deliveryPayment.payment.how.step2', label: 'Шаг оплаты 2' },
      { type: 'text', key: 'deliveryPayment.payment.how.step3', label: 'Шаг оплаты 3' },
      { type: 'text', key: 'deliveryPayment.payment.how.step4', label: 'Шаг оплаты 4' },
      { type: 'text', key: 'deliveryPayment.payment.security.title', label: 'Заголовок «Безопасность платежей»' },
      { type: 'text', key: 'deliveryPayment.payment.security.intro', label: 'Безопасность — вводный текст', multiline: true },
      { type: 'text', key: 'deliveryPayment.payment.security.item1', label: 'Безопасность — пункт 1', multiline: true },
      { type: 'text', key: 'deliveryPayment.payment.security.item2', label: 'Безопасность — пункт 2' },
      { type: 'text', key: 'deliveryPayment.payment.security.item3', label: 'Безопасность — пункт 3' },
      { type: 'text', key: 'deliveryPayment.payment.security.note', label: 'Безопасность — примечание', multiline: true },
      { type: 'text', key: 'deliveryPayment.support.title', label: 'Заголовок «Вопросы по оплате»' },
      { type: 'text', key: 'deliveryPayment.support.intro', label: 'Вопросы по оплате — вводный текст', multiline: true },
    ],
  },
  {
    id: 'header-logo',
    title: 'Логотип',
    entries: [
      { type: 'image', src: '/logo-2026.svg', label: 'Логотип (светлая тема)' },
      { type: 'image', src: '/logo-white-2026.svg', label: 'Логотип (тёмная тема)' },
    ],
  },
  {
    id: 'store-riga-office',
    title: 'Магазин — Рига Офис',
    entries: [
      { type: 'text', key: 'stores.riga-office.name', label: 'Название' },
      { type: 'text', key: 'stores.riga-office.hours1', label: 'Часы работы — строка 1' },
      { type: 'text', key: 'stores.riga-office.hours2', label: 'Часы работы — строка 2' },
      { type: 'text', key: 'stores.riga-office.hours3', label: 'Часы работы — строка 3' },
      { type: 'text', key: 'stores.riga-office.phone', label: 'Телефон' },
      { type: 'text', key: 'stores.riga-office.address', label: 'Адрес', defaults: storeAddressDefaults('riga-office') },
      { type: 'image', src: '/stores/riga-office.jpg', label: 'Фотография' },
    ],
  },
  {
    id: 'store-imanta',
    title: 'Магазин — Рига (Иманта)',
    entries: [
      { type: 'text', key: 'stores.imanta.name', label: 'Название' },
      { type: 'text', key: 'stores.imanta.hours1', label: 'Часы работы — строка 1' },
      { type: 'text', key: 'stores.imanta.hours2', label: 'Часы работы — строка 2' },
      { type: 'text', key: 'stores.imanta.hours3', label: 'Часы работы — строка 3' },
      { type: 'text', key: 'stores.imanta.phone', label: 'Телефон' },
      { type: 'text', key: 'stores.imanta.address', label: 'Адрес', defaults: storeAddressDefaults('imanta') },
      { type: 'image', src: '/stores/imanta.jpg', label: 'Фотография' },
    ],
  },
  {
    id: 'store-plavnieki',
    title: 'Магазин — Рига (Плявниеки)',
    entries: [
      { type: 'text', key: 'stores.plavnieki.name', label: 'Название' },
      { type: 'text', key: 'stores.plavnieki.hours1', label: 'Часы работы — строка 1' },
      { type: 'text', key: 'stores.plavnieki.hours2', label: 'Часы работы — строка 2' },
      { type: 'text', key: 'stores.plavnieki.hours3', label: 'Часы работы — строка 3' },
      { type: 'text', key: 'stores.plavnieki.phone', label: 'Телефон' },
      { type: 'text', key: 'stores.plavnieki.address', label: 'Адрес', defaults: storeAddressDefaults('plavnieki') },
      { type: 'image', src: '/stores/plavnieki.jpg', label: 'Фотография' },
    ],
  },
  {
    id: 'store-daugavpils',
    title: 'Магазин — Даугавпилс',
    entries: [
      { type: 'text', key: 'stores.daugavpils.name', label: 'Название' },
      { type: 'text', key: 'stores.daugavpils.hours1', label: 'Часы работы — строка 1' },
      { type: 'text', key: 'stores.daugavpils.hours2', label: 'Часы работы — строка 2' },
      { type: 'text', key: 'stores.daugavpils.hours3', label: 'Часы работы — строка 3' },
      { type: 'text', key: 'stores.daugavpils.phone', label: 'Телефон' },
      { type: 'text', key: 'stores.daugavpils.address', label: 'Адрес', defaults: storeAddressDefaults('daugavpils') },
      { type: 'image', src: '/stores/daugavpils.jpg', label: 'Фотография' },
    ],
  },
  {
    id: 'store-liepaja',
    title: 'Магазин — Лиепая',
    entries: [
      { type: 'text', key: 'stores.liepaja.name', label: 'Название' },
      { type: 'text', key: 'stores.liepaja.hours1', label: 'Часы работы — строка 1' },
      { type: 'text', key: 'stores.liepaja.hours2', label: 'Часы работы — строка 2' },
      { type: 'text', key: 'stores.liepaja.hours3', label: 'Часы работы — строка 3' },
      { type: 'text', key: 'stores.liepaja.phone', label: 'Телефон' },
      { type: 'text', key: 'stores.liepaja.address', label: 'Адрес', defaults: storeAddressDefaults('liepaja') },
      { type: 'image', src: '/stores/liepaja.jpg', label: 'Фотография' },
    ],
  },
  {
    id: 'store-valmiera',
    title: 'Магазин — Валмиера',
    entries: [
      { type: 'text', key: 'stores.valmiera.name', label: 'Название' },
      { type: 'text', key: 'stores.valmiera.hours1', label: 'Часы работы — строка 1' },
      { type: 'text', key: 'stores.valmiera.hours2', label: 'Часы работы — строка 2' },
      { type: 'text', key: 'stores.valmiera.hours3', label: 'Часы работы — строка 3' },
      { type: 'text', key: 'stores.valmiera.phone', label: 'Телефон' },
      { type: 'text', key: 'stores.valmiera.address', label: 'Адрес', defaults: storeAddressDefaults('valmiera') },
      { type: 'image', src: '/stores/valmiera.jpg', label: 'Фотография' },
    ],
  },
  {
    id: 'store-rezekne',
    title: 'Магазин — Резекне',
    entries: [
      { type: 'text', key: 'stores.rezekne.name', label: 'Название' },
      { type: 'text', key: 'stores.rezekne.hours1', label: 'Часы работы — строка 1' },
      { type: 'text', key: 'stores.rezekne.hours2', label: 'Часы работы — строка 2' },
      { type: 'text', key: 'stores.rezekne.hours3', label: 'Часы работы — строка 3' },
      { type: 'text', key: 'stores.rezekne.phone', label: 'Телефон' },
      { type: 'text', key: 'stores.rezekne.address', label: 'Адрес', defaults: storeAddressDefaults('rezekne') },
      { type: 'image', src: '/stores/rezekne.jpg', label: 'Фотография' },
    ],
  },
  {
    id: 'store-jelgava',
    title: 'Магазин — Елгава',
    entries: [
      { type: 'text', key: 'stores.jelgava.name', label: 'Название' },
      { type: 'text', key: 'stores.jelgava.hours1', label: 'Часы работы — строка 1' },
      { type: 'text', key: 'stores.jelgava.hours2', label: 'Часы работы — строка 2' },
      { type: 'text', key: 'stores.jelgava.hours3', label: 'Часы работы — строка 3' },
      { type: 'text', key: 'stores.jelgava.phone', label: 'Телефон' },
      { type: 'text', key: 'stores.jelgava.address', label: 'Адрес', defaults: storeAddressDefaults('jelgava') },
      { type: 'image', src: '/stores/jelgava.jpg', label: 'Фотография' },
    ],
  },
  {
    id: 'legal-pages',
    title: 'Юридические страницы',
    entries: [
      { type: 'text', key: 'legal.privacy.title', label: 'Конфиденциальность — заголовок', defaults: { ru: privacyContent.ru.title, en: privacyContent.en.title, lv: privacyContent.lv.title } },
      { type: 'text', key: 'legal.privacy.html', label: 'Конфиденциальность — HTML', multiline: true, defaults: { ru: privacyContent.ru.html, en: privacyContent.en.html, lv: privacyContent.lv.html } },
      { type: 'text', key: 'legal.terms.title', label: 'Условия — заголовок', defaults: { ru: termsContent.ru.title, en: termsContent.en.title, lv: termsContent.lv.title } },
      { type: 'text', key: 'legal.terms.html', label: 'Условия — HTML', multiline: true, defaults: { ru: termsContent.ru.html, en: termsContent.en.html, lv: termsContent.lv.html } },
      { type: 'text', key: 'legal.cookies.title', label: 'Cookie — заголовок', defaults: { ru: cookieContent.ru.title, en: cookieContent.en.title, lv: cookieContent.lv.title } },
      { type: 'text', key: 'legal.cookies.html', label: 'Cookie — HTML', multiline: true, defaults: { ru: cookieContent.ru.html, en: cookieContent.en.html, lv: cookieContent.lv.html } },
      { type: 'text', key: 'legal.returnPolicy.title', label: 'Возврат — заголовок', defaults: { ru: returnPolicyContent.ru.title, en: returnPolicyContent.en.title, lv: returnPolicyContent.lv.title } },
      { type: 'text', key: 'legal.returnPolicy.html', label: 'Возврат — HTML', multiline: true, defaults: { ru: returnPolicyContent.ru.html, en: returnPolicyContent.en.html, lv: returnPolicyContent.lv.html } },
    ],
  },
]
