// Curated registry of admin-editable site content. Each text entry names a
// translation key already rendered through t(); each image entry names a base
// src already passed through resolveImageSrc(). The /admin/content page renders
// this registry so admins can edit content without knowing keys or paths.
// When new t()-wired content is added to the site, add it here too —
// lib/content-registry.test.ts validates every key and file path.

export type ContentEntry =
  | { type: 'text'; key: string; label: string; multiline?: boolean }
  | { type: 'image'; src: string; label: string }

export type ContentSection = {
  id: string
  title: string
  entries: ContentEntry[]
}

export const CONTENT_REGISTRY: ContentSection[] = [
  {
    id: 'home-hero',
    title: 'Главная — Hero',
    entries: [
      { type: 'text', key: 'hero.title', label: 'Заголовок' },
      { type: 'text', key: 'hero.subtitle', label: 'Подзаголовок' },
      { type: 'text', key: 'hero.alt', label: 'Alt-текст фоновой картинки' },
      { type: 'image', src: '/hero.jpg', label: 'Фоновая картинка' },
    ],
  },
  {
    id: 'home-benefits',
    title: 'Главная — Преимущества',
    entries: [
      { type: 'text', key: 'benefits.deliveryFree', label: 'Бесплатная доставка' },
      { type: 'text', key: 'benefits.consultationMain', label: 'Консультации' },
      { type: 'text', key: 'benefits.processingFast', label: 'Быстрая обработка' },
      { type: 'text', key: 'benefits.inStock', label: 'Товары на складе' },
      { type: 'text', key: 'benefits.brands100', label: 'Оригинальные бренды' },
      { type: 'text', key: 'benefits.bonusPoints', label: 'Бонусные баллы' },
      { type: 'image', src: '/icons/delivery.svg', label: 'Иконка «Доставка»' },
      { type: 'image', src: '/icons/consulting.svg', label: 'Иконка «Консультации»' },
      { type: 'image', src: '/icons/orders.svg', label: 'Иконка «Обработка заказов»' },
      { type: 'image', src: '/icons/goods.svg', label: 'Иконка «Товары на складе»' },
      { type: 'image', src: '/icons/originals.svg', label: 'Иконка «Оригинальные бренды»' },
      { type: 'image', src: '/icons/bonuses.svg', label: 'Иконка «Бонусы»' },
    ],
  },
  {
    id: 'about',
    title: 'О нас',
    entries: [
      { type: 'text', key: 'about.title', label: 'Заголовок страницы' },
      { type: 'text', key: 'about.welcome.title', label: 'Приветствие — заголовок' },
      { type: 'text', key: 'about.welcome.p1', label: 'Приветствие — абзац 1', multiline: true },
      { type: 'text', key: 'about.welcome.p2', label: 'Приветствие — абзац 2', multiline: true },
      { type: 'text', key: 'about.storesInfo', label: 'Текст о магазинах', multiline: true },
      { type: 'text', key: 'about.storesButton', label: 'Кнопка «Магазины»' },
      { type: 'text', key: 'about.why.title', label: 'Почему мы — заголовок' },
      { type: 'text', key: 'about.why.item1', label: 'Почему мы — пункт 1' },
      { type: 'text', key: 'about.why.item2', label: 'Почему мы — пункт 2' },
      { type: 'text', key: 'about.why.item3', label: 'Почему мы — пункт 3' },
      { type: 'text', key: 'about.why.item4', label: 'Почему мы — пункт 4' },
      { type: 'text', key: 'about.why.item5', label: 'Почему мы — пункт 5' },
    ],
  },
  {
    id: 'faq',
    title: 'FAQ',
    entries: [
      { type: 'text', key: 'faq.site.title', label: 'Заголовок блока' },
      { type: 'text', key: 'faq.site.subtitle', label: 'Подзаголовок блока' },
      // Нумерация с пропусками (нет q3/q9) — ровно как в components/FAQSection.tsx
      { type: 'text', key: 'faq.site.q1', label: 'Вопрос 1' },
      { type: 'text', key: 'faq.site.a1', label: 'Ответ 1', multiline: true },
      { type: 'text', key: 'faq.site.q2', label: 'Вопрос 2' },
      { type: 'text', key: 'faq.site.a2', label: 'Ответ 2', multiline: true },
      { type: 'text', key: 'faq.site.q4', label: 'Вопрос 4' },
      { type: 'text', key: 'faq.site.a4', label: 'Ответ 4', multiline: true },
      { type: 'text', key: 'faq.site.q5', label: 'Вопрос 5' },
      { type: 'text', key: 'faq.site.a5', label: 'Ответ 5', multiline: true },
      { type: 'text', key: 'faq.site.q6', label: 'Вопрос 6' },
      { type: 'text', key: 'faq.site.a6', label: 'Ответ 6', multiline: true },
      { type: 'text', key: 'faq.site.q7', label: 'Вопрос 7' },
      { type: 'text', key: 'faq.site.a7', label: 'Ответ 7', multiline: true },
      { type: 'text', key: 'faq.site.q8', label: 'Вопрос 8' },
      { type: 'text', key: 'faq.site.a8', label: 'Ответ 8', multiline: true },
      { type: 'text', key: 'faq.site.q10', label: 'Вопрос 10' },
      { type: 'text', key: 'faq.site.a10', label: 'Ответ 10', multiline: true },
      { type: 'text', key: 'faq.site.q11', label: 'Вопрос 11' },
      { type: 'text', key: 'faq.site.a11', label: 'Ответ 11', multiline: true },
      { type: 'text', key: 'faq.site.q12', label: 'Вопрос 12' },
      { type: 'text', key: 'faq.site.a12', label: 'Ответ 12', multiline: true },
    ],
  },
  {
    id: 'newsletter',
    title: 'Рассылка',
    entries: [
      { type: 'text', key: 'newsletter.title', label: 'Заголовок' },
      { type: 'text', key: 'newsletter.subtitle', label: 'Подзаголовок' },
      { type: 'text', key: 'newsletter.placeholder', label: 'Плейсхолдер поля email' },
      { type: 'text', key: 'newsletter.subscribe', label: 'Кнопка подписки' },
      { type: 'text', key: 'newsletter.consentPrefix', label: 'Текст согласия' },
      { type: 'text', key: 'newsletter.consentLinkLabel', label: 'Ссылка в согласии' },
    ],
  },
  {
    id: 'footer',
    title: 'Футер',
    entries: [
      { type: 'text', key: 'footer.about', label: 'О компании', multiline: true },
      { type: 'text', key: 'footer.contact', label: 'Заголовок «Контакты»' },
      { type: 'text', key: 'footer.privacy', label: 'Политика конфиденциальности' },
      { type: 'text', key: 'footer.terms', label: 'Условия использования' },
      { type: 'text', key: 'footer.allRightsReserved', label: 'Копирайт (текст после года)' },
    ],
  },
  {
    id: 'contact',
    title: 'Контакты',
    entries: [
      { type: 'text', key: 'contact.title', label: 'Заголовок страницы' },
      { type: 'text', key: 'contact.info', label: 'Вводный текст', multiline: true },
      { type: 'text', key: 'contact.formTitle', label: 'Заголовок формы' },
      { type: 'text', key: 'contact.faq.q1', label: 'FAQ — вопрос 1' },
      { type: 'text', key: 'contact.faq.a1', label: 'FAQ — ответ 1', multiline: true },
      { type: 'text', key: 'contact.faq.q2', label: 'FAQ — вопрос 2' },
      { type: 'text', key: 'contact.faq.a2', label: 'FAQ — ответ 2', multiline: true },
      { type: 'text', key: 'contact.faq.q3', label: 'FAQ — вопрос 3' },
      { type: 'text', key: 'contact.faq.a3', label: 'FAQ — ответ 3', multiline: true },
    ],
  },
  {
    id: 'delivery',
    title: 'Доставка',
    entries: [
      { type: 'text', key: 'deliveryPayment.methods.title', label: 'Заголовок «Способы доставки»' },
      { type: 'text', key: 'deliveryPayment.methods.courierLatvia.label', label: 'Курьер по Латвии — заголовок' },
      { type: 'text', key: 'deliveryPayment.methods.courierLatvia.price', label: 'Курьер по Латвии — цена' },
      { type: 'text', key: 'deliveryPayment.methods.courierLatvia.freeNote', label: 'Курьер по Латвии — условие бесплатной доставки', multiline: true },
      { type: 'text', key: 'deliveryPayment.methods.omniva.label', label: 'OMNIVA — заголовок' },
      { type: 'text', key: 'deliveryPayment.methods.omniva.price', label: 'OMNIVA — цена' },
      { type: 'text', key: 'deliveryPayment.methods.omniva.maxSize', label: 'OMNIVA — макс. размер' },
      { type: 'text', key: 'deliveryPayment.methods.omniva.weight', label: 'OMNIVA — макс. вес' },
      { type: 'text', key: 'deliveryPayment.methods.pickup.label', label: 'Самовывоз — заголовок' },
      { type: 'text', key: 'deliveryPayment.methods.pickup.intro', label: 'Самовывоз — вводный текст', multiline: true },
      { type: 'text', key: 'deliveryPayment.rules.title', label: 'Заголовок «Правила курьерской доставки»' },
      { type: 'text', key: 'deliveryPayment.rules.item1', label: 'Правило 1', multiline: true },
      { type: 'text', key: 'deliveryPayment.rules.item2', label: 'Правило 2', multiline: true },
      { type: 'text', key: 'deliveryPayment.rules.item3', label: 'Правило 3', multiline: true },
      { type: 'text', key: 'deliveryPayment.rules.item4', label: 'Правило 4', multiline: true },
      { type: 'text', key: 'deliveryPayment.rules.item5', label: 'Правило 5', multiline: true },
      { type: 'text', key: 'deliveryPayment.rules.item6', label: 'Правило 6', multiline: true },
      { type: 'text', key: 'deliveryPayment.rules.item7', label: 'Правило 7', multiline: true },
      { type: 'text', key: 'deliveryPayment.rules.item8', label: 'Правило 8', multiline: true },
      { type: 'text', key: 'deliveryPayment.rules.item9', label: 'Правило 9', multiline: true },
      { type: 'text', key: 'deliveryPayment.rules.item10', label: 'Правило 10' },
      { type: 'text', key: 'deliveryPayment.return.title', label: 'Заголовок «Возврат товара»' },
      { type: 'text', key: 'deliveryPayment.return.intro', label: 'Возврат — вводный текст', multiline: true },
      { type: 'text', key: 'deliveryPayment.return.conditionsTitle', label: 'Возврат — заголовок условий' },
      { type: 'text', key: 'deliveryPayment.return.condition1', label: 'Условие возврата 1' },
      { type: 'text', key: 'deliveryPayment.return.condition2', label: 'Условие возврата 2' },
      { type: 'text', key: 'deliveryPayment.return.condition3', label: 'Условие возврата 3' },
      { type: 'text', key: 'deliveryPayment.return.refundNote', label: 'Возврат — про возврат средств', multiline: true },
      { type: 'text', key: 'deliveryPayment.return.exceptionIntro', label: 'Возврат — исключения, вводный текст', multiline: true },
      { type: 'text', key: 'deliveryPayment.return.exceptionItem1', label: 'Возврат — исключение 1', multiline: true },
      { type: 'text', key: 'deliveryPayment.contacts.title', label: 'Заголовок «Вопросы по доставке»' },
      { type: 'text', key: 'deliveryPayment.contacts.intro', label: 'Вопросы по доставке — вводный текст' },
    ],
  },
  {
    id: 'payment',
    title: 'Оплата',
    entries: [
      { type: 'text', key: 'deliveryPayment.payment.methods.title', label: 'Заголовок «Способы оплаты»' },
      { type: 'text', key: 'deliveryPayment.payment.card.label', label: 'Оплата картой — заголовок' },
      { type: 'text', key: 'deliveryPayment.payment.card.note', label: 'Оплата картой — пояснение', multiline: true },
      { type: 'text', key: 'deliveryPayment.payment.cash.label', label: 'Оплата наличными — заголовок' },
      { type: 'text', key: 'deliveryPayment.payment.cash.note', label: 'Оплата наличными — пояснение', multiline: true },
      { type: 'text', key: 'deliveryPayment.payment.transfer.label', label: 'Банковский перевод — заголовок' },
      { type: 'text', key: 'deliveryPayment.payment.transfer.note1', label: 'Банковский перевод — пояснение 1', multiline: true },
      { type: 'text', key: 'deliveryPayment.payment.transfer.note2', label: 'Банковский перевод — пояснение 2', multiline: true },
      { type: 'text', key: 'deliveryPayment.payment.transfer.requisitesTitle', label: 'Заголовок «Реквизиты для оплаты»' },
      { type: 'text', key: 'deliveryPayment.payment.leasing.label', label: 'Lateko Līzings — заголовок' },
      { type: 'text', key: 'deliveryPayment.payment.leasing.note', label: 'Lateko Līzings — пояснение', multiline: true },
      { type: 'text', key: 'deliveryPayment.payment.how.title', label: 'Заголовок «Как происходит оплата»' },
      { type: 'text', key: 'deliveryPayment.payment.how.step1', label: 'Шаг оплаты 1' },
      { type: 'text', key: 'deliveryPayment.payment.how.step2', label: 'Шаг оплаты 2' },
      { type: 'text', key: 'deliveryPayment.payment.how.step3', label: 'Шаг оплаты 3' },
      { type: 'text', key: 'deliveryPayment.payment.how.step4', label: 'Шаг оплаты 4' },
      { type: 'text', key: 'deliveryPayment.payment.security.title', label: 'Заголовок «Безопасность платежей»' },
      { type: 'text', key: 'deliveryPayment.payment.security.intro', label: 'Безопасность — вводный текст', multiline: true },
      { type: 'text', key: 'deliveryPayment.payment.security.item1', label: 'Безопасность — пункт 1', multiline: true },
      { type: 'text', key: 'deliveryPayment.payment.security.item2', label: 'Безопасность — пункт 2' },
      { type: 'text', key: 'deliveryPayment.payment.security.item3', label: 'Безопасность — пункт 3' },
      { type: 'text', key: 'deliveryPayment.payment.security.note', label: 'Безопасность — примечание', multiline: true },
      { type: 'text', key: 'deliveryPayment.support.title', label: 'Заголовок «Вопросы по оплате»' },
      { type: 'text', key: 'deliveryPayment.support.intro', label: 'Вопросы по оплате — вводный текст', multiline: true },
      { type: 'text', key: 'deliveryPayment.support.skypeLabel', label: 'Лейбл «Skype»' },
    ],
  },
  {
    id: 'header-logo',
    title: 'Логотип',
    entries: [
      { type: 'image', src: '/logo.svg', label: 'Логотип (светлая тема)' },
      { type: 'image', src: '/logo-white.svg', label: 'Логотип (тёмная тема)' },
    ],
  },
  {
    id: 'store-riga-office',
    title: 'Магазин — Рига Офис',
    entries: [
      { type: 'text', key: 'stores.riga-office.name', label: 'Название' },
      { type: 'text', key: 'stores.riga-office.hours1', label: 'Часы работы — строка 1' },
      { type: 'text', key: 'stores.riga-office.hours2', label: 'Часы работы — строка 2' },
      { type: 'text', key: 'stores.riga-office.hours3', label: 'Часы работы — строка 3' },
      { type: 'text', key: 'stores.riga-office.phone', label: 'Телефон' },
    ],
  },
  {
    id: 'store-imanta',
    title: 'Магазин — Рига (Иманта)',
    entries: [
      { type: 'text', key: 'stores.imanta.name', label: 'Название' },
      { type: 'text', key: 'stores.imanta.hours1', label: 'Часы работы — строка 1' },
      { type: 'text', key: 'stores.imanta.hours2', label: 'Часы работы — строка 2' },
      { type: 'text', key: 'stores.imanta.hours3', label: 'Часы работы — строка 3' },
      { type: 'text', key: 'stores.imanta.phone', label: 'Телефон' },
    ],
  },
  {
    id: 'store-plavnieki',
    title: 'Магазин — Рига (Плявниеки)',
    entries: [
      { type: 'text', key: 'stores.plavnieki.name', label: 'Название' },
      { type: 'text', key: 'stores.plavnieki.hours1', label: 'Часы работы — строка 1' },
      { type: 'text', key: 'stores.plavnieki.hours2', label: 'Часы работы — строка 2' },
      { type: 'text', key: 'stores.plavnieki.hours3', label: 'Часы работы — строка 3' },
      { type: 'text', key: 'stores.plavnieki.phone', label: 'Телефон' },
    ],
  },
  {
    id: 'store-daugavpils',
    title: 'Магазин — Даугавпилс',
    entries: [
      { type: 'text', key: 'stores.daugavpils.name', label: 'Название' },
      { type: 'text', key: 'stores.daugavpils.hours1', label: 'Часы работы — строка 1' },
      { type: 'text', key: 'stores.daugavpils.hours2', label: 'Часы работы — строка 2' },
      { type: 'text', key: 'stores.daugavpils.hours3', label: 'Часы работы — строка 3' },
      { type: 'text', key: 'stores.daugavpils.phone', label: 'Телефон' },
    ],
  },
  {
    id: 'store-liepaja',
    title: 'Магазин — Лиепая',
    entries: [
      { type: 'text', key: 'stores.liepaja.name', label: 'Название' },
      { type: 'text', key: 'stores.liepaja.hours1', label: 'Часы работы — строка 1' },
      { type: 'text', key: 'stores.liepaja.hours2', label: 'Часы работы — строка 2' },
      { type: 'text', key: 'stores.liepaja.hours3', label: 'Часы работы — строка 3' },
      { type: 'text', key: 'stores.liepaja.phone', label: 'Телефон' },
    ],
  },
  {
    id: 'store-valmiera',
    title: 'Магазин — Валмиера',
    entries: [
      { type: 'text', key: 'stores.valmiera.name', label: 'Название' },
      { type: 'text', key: 'stores.valmiera.hours1', label: 'Часы работы — строка 1' },
      { type: 'text', key: 'stores.valmiera.hours2', label: 'Часы работы — строка 2' },
      { type: 'text', key: 'stores.valmiera.hours3', label: 'Часы работы — строка 3' },
      { type: 'text', key: 'stores.valmiera.phone', label: 'Телефон' },
    ],
  },
  {
    id: 'store-rezekne',
    title: 'Магазин — Резекне',
    entries: [
      { type: 'text', key: 'stores.rezekne.name', label: 'Название' },
      { type: 'text', key: 'stores.rezekne.hours1', label: 'Часы работы — строка 1' },
      { type: 'text', key: 'stores.rezekne.hours2', label: 'Часы работы — строка 2' },
      { type: 'text', key: 'stores.rezekne.hours3', label: 'Часы работы — строка 3' },
      { type: 'text', key: 'stores.rezekne.phone', label: 'Телефон' },
    ],
  },
  {
    id: 'store-jelgava',
    title: 'Магазин — Елгава',
    entries: [
      { type: 'text', key: 'stores.jelgava.name', label: 'Название' },
      { type: 'text', key: 'stores.jelgava.hours1', label: 'Часы работы — строка 1' },
      { type: 'text', key: 'stores.jelgava.hours2', label: 'Часы работы — строка 2' },
      { type: 'text', key: 'stores.jelgava.hours3', label: 'Часы работы — строка 3' },
      { type: 'text', key: 'stores.jelgava.phone', label: 'Телефон' },
    ],
  },
]
