import { cache } from 'react'
import { type Product, type BadgeType, type CategoryType } from '@/data/products'
import { prisma } from '@/lib/prisma'
import { Prisma } from '@/generated/prisma/client'
import type { Product as PrismaProduct } from '@/generated/prisma/client'
import productSubcategories from '@/data/product-subcategories.json'
import { toNum, toNumOrNull } from '@/lib/decimal'

const SUBCATEGORY_BY_PRODUCT_ID = productSubcategories as Record<string, string>

export function mapDbToProduct(p: PrismaProduct): Product {
  return {
    id: p.id,
    title: p.title,
    titleKey: p.titleKey ?? undefined,
    titleEn: p.titleEn ?? undefined,
    titleLv: p.titleLv ?? undefined,
    description: p.description ?? undefined,
    brand: p.brand,
    price: toNum(p.price),
    oldPrice: toNumOrNull(p.oldPrice) ?? undefined,
    rating: p.rating,
    ratingCount: p.ratingCount,
    reviewCount: p.reviewCount,
    image: p.image ?? undefined,
    images: p.images,
    metaTitle: p.metaTitle ?? undefined,
    metaDescription: p.metaDescription ?? undefined,
    ogImage: p.ogImage ?? undefined,
    ogAlt: p.ogAlt ?? undefined,
    badges: p.badges as BadgeType[],
    category: p.category as CategoryType,
    subcategory: SUBCATEGORY_BY_PRODUCT_ID[p.id],
    stock: p.stock,
    isActive: p.isActive,
    barcode: p.barcode ?? undefined,
    relatedProductIds: p.relatedProductIds,
    oftenBoughtTogether: p.oftenBoughtTogether,
    minOrderQuantities: (p.minOrderQuantities ?? undefined) as Record<string, number> | undefined,
    technicalSpecs: (p.technicalSpecs ?? undefined) as Record<string, string> | undefined,
    bulkPricingTiers: (p.bulkPricingTiers ?? undefined) as Array<{ quantity: number; pricePerUnit: number }> | undefined,
    demoVideo: (p.demoVideo ?? undefined) as Array<{ src: string; poster?: string }> | undefined,
    distributorName: (p.distributorName ?? undefined) as { ru: string; en: string; lv: string } | undefined,
    distributorAddress: (p.distributorAddress ?? undefined) as { ru: string; en: string; lv: string } | undefined,
    sku: p.sku ?? undefined,
    unitOfMeasure: p.unitOfMeasure ?? undefined,
    certificates: p.certificates,
    packagingSize: p.packagingSize ?? undefined,
    compatibleEquipment: p.compatibleEquipment,
    manufacturerName: p.manufacturerName ?? undefined,
    manufacturerAddress: p.manufacturerAddress ?? undefined,
    manufacturerEmail: p.manufacturerEmail ?? undefined,
    distributorEmail: p.distributorEmail ?? undefined,
    bonusRate: p.bonusRate ?? undefined,
    feature1: p.feature1 ?? undefined,
    feature1En: p.feature1En ?? undefined,
    feature1Lv: p.feature1Lv ?? undefined,
    feature2: p.feature2 ?? undefined,
    feature2En: p.feature2En ?? undefined,
    feature2Lv: p.feature2Lv ?? undefined,
    feature3: p.feature3 ?? undefined,
    feature3En: p.feature3En ?? undefined,
    feature3Lv: p.feature3Lv ?? undefined,
    feature4: p.feature4 ?? undefined,
    feature4En: p.feature4En ?? undefined,
    feature4Lv: p.feature4Lv ?? undefined,
    specVolume: p.specVolume ?? undefined,
    specType: p.specType ?? undefined,
    specCountry: p.specCountry ?? undefined,
  }
}

export function mapProductToDbCreate(p: Product, isCustom = false): any {
  return {
    id: p.id,
    title: p.title,
    titleKey: p.titleKey ?? null,
    titleEn: p.titleEn ?? null,
    titleLv: p.titleLv ?? null,
    description: p.description ?? null,
    brand: p.brand,
    price: p.price,
    oldPrice: p.oldPrice ?? null,
    rating: p.rating,
    ratingCount: p.ratingCount ?? 0,
    reviewCount: p.reviewCount ?? 0,
    image: p.image ?? null,
    images: p.images ?? [],
    metaTitle: p.metaTitle ?? null,
    metaDescription: p.metaDescription ?? null,
    ogImage: p.ogImage ?? null,
    ogAlt: p.ogAlt ?? null,
    badges: (p.badges ?? []) as string[],
    category: p.category,
    stock: p.stock,
    barcode: p.barcode ?? null,
    relatedProductIds: p.relatedProductIds ?? [],
    oftenBoughtTogether: p.oftenBoughtTogether ?? [],
    minOrderQuantities: p.minOrderQuantities ?? null,
    technicalSpecs: p.technicalSpecs ?? null,
    bulkPricingTiers: p.bulkPricingTiers ?? null,
    demoVideo: p.demoVideo ?? null,
    distributorName: p.distributorName ?? null,
    distributorAddress: p.distributorAddress ?? null,
    sku: p.sku ?? null,
    unitOfMeasure: p.unitOfMeasure ?? null,
    certificates: p.certificates ?? [],
    packagingSize: p.packagingSize ?? null,
    compatibleEquipment: p.compatibleEquipment ?? [],
    manufacturerName: p.manufacturerName ?? null,
    manufacturerAddress: p.manufacturerAddress ?? null,
    manufacturerEmail: p.manufacturerEmail ?? null,
    distributorEmail: p.distributorEmail ?? null,
    bonusRate: p.bonusRate ?? null,
    feature1: p.feature1 ?? null,
    feature1En: p.feature1En ?? null,
    feature1Lv: p.feature1Lv ?? null,
    feature2: p.feature2 ?? null,
    feature2En: p.feature2En ?? null,
    feature2Lv: p.feature2Lv ?? null,
    feature3: p.feature3 ?? null,
    feature3En: p.feature3En ?? null,
    feature3Lv: p.feature3Lv ?? null,
    feature4: p.feature4 ?? null,
    feature4En: p.feature4En ?? null,
    feature4Lv: p.feature4Lv ?? null,
    specVolume: p.specVolume ?? null,
    specType: p.specType ?? null,
    specCountry: p.specCountry ?? null,
    isCustom,
    isDeleted: false,
    isActive: p.isActive ?? true,
  }
}
