import { randomUUID } from 'node:crypto'
import type { Prisma } from '@/generated/prisma/client'
import type { ExtendedPrismaClient, ExtendedTransactionClient } from '../prisma'
import type { ErpProduct } from './erp-adapter'
import { getErpExtraData, mergeEnabledPriceTiers, type ErpExtraData } from './erp-extra-data-store'
import { getSyncRules, selectedStock } from './sync-rules'
import { FIFTH_WAVE_SIZE, type FifthWaveAllowlist } from './fifth-wave-backfill'

export type FifthWaveScopeProduct={id:string;externalId:string|null;sku:string|null;price:unknown;stock:number;isDeleted:boolean;isActive:boolean}
export type FifthWavePlan={rows:Array<{id:string;externalId:string;productSku:string;price:number;stock:number;originalPrice:number;originalStock:number}>;extraData:Record<string,ErpExtraData>;metrics:{scope:number;inserts:number;deactivations:number;outsideScopeChanges:number;predictedProductUpdates:number;predictedErpRecords:number;predictedErpSemanticUpdates:number;price2Positive:number;price2Zero:number;priceWouldChange:number;priceUnchanged:number;over50PercentChanges:number;zeroPriceRegressions:number;stockWouldChange:number;stockUnchanged:number;positiveToZero:number;zeroToPositive:number;resultingStockZero:number;stockFormulaMismatches:number}}
export function buildFifthWavePlan(allowlist:FifthWaveAllowlist,feed:ErpProduct[],products:FifthWaveScopeProduct[],currentExtra:Record<string,ErpExtraData>,phase:'preview-before-backfill'|'post-backfill'):FifthWavePlan{
  if(products.length!==FIFTH_WAVE_SIZE)throw new Error(`DATABASE_SCOPE_SIZE_MISMATCH:${products.length}`);const feedCounts=new Map<string,number>();for(const item of feed)feedCounts.set(item.externalId,(feedCounts.get(item.externalId)??0)+1);const feedById=new Map(feed.map(item=>[item.externalId,item])),dbById=new Map(products.map(product=>[product.id,product])),extraData={...currentExtra},rows:FifthWavePlan['rows']=[],rules=getSyncRules();let predictedErpSemanticUpdates=0,price2Positive=0,price2Zero=0,priceWouldChange=0,priceUnchanged=0,over50PercentChanges=0,zeroPriceRegressions=0,stockWouldChange=0,stockUnchanged=0,positiveToZero=0,zeroToPositive=0,resultingStockZero=0,stockFormulaMismatches=0
  for(const entry of allowlist.entries){const db=dbById.get(entry.productId),item=feedById.get(entry.externalIdToSet);if(!db||!item)throw new Error(`SCOPE_MEMBER_MISSING:${entry.productId}`);const expectedExternal=phase==='post-backfill'?entry.externalIdToSet:null;if(db.isDeleted||db.externalId!==expectedExternal||db.sku!==entry.productSku||item.externalId!==entry.xmlSku)throw new Error(`IMMUTABLE_SCOPE_MISMATCH:${entry.productId}`);if(feedCounts.get(item.externalId)!==1)throw new Error(`DUPLICATE_XML_SKU:${item.externalId}`);const formulaStock=selectedStock(item.warehouseQuantities??{});if(formulaStock!==item.stock)stockFormulaMismatches++;const originalPrice=Number(db.price),price=item.price>0?item.price:originalPrice;if(item.price>0)price2Positive++;else price2Zero++;if(price===originalPrice)priceUnchanged++;else priceWouldChange++;if(originalPrice>0&&Math.abs(price-originalPrice)/originalPrice>.5)over50PercentChanges++;if(originalPrice>0&&price===0)zeroPriceRegressions++;if(item.stock===db.stock)stockUnchanged++;else stockWouldChange++;if(db.stock>0&&item.stock===0)positiveToZero++;if(db.stock===0&&item.stock>0)zeroToPositive++;if(item.stock===0)resultingStockZero++;rows.push({id:db.id,externalId:entry.externalIdToSet,productSku:entry.productSku,price,stock:item.stock,originalPrice,originalStock:db.stock});const nextExtra=mergeEnabledPriceTiers(currentExtra[item.externalId],{prices:item.prices??{price1:0,price2:0,price3:0,price4:0},warehouseQuantities:item.warehouseQuantities??{}},rules.enabledPriceTiers);if(JSON.stringify(currentExtra[item.externalId])!==JSON.stringify(nextExtra))predictedErpSemanticUpdates++;extraData[item.externalId]=nextExtra}if(stockFormulaMismatches||rows.length!==FIFTH_WAVE_SIZE)throw new Error(`PLAN_GATE_FAILED:${stockFormulaMismatches}:${rows.length}`);return{rows,extraData,metrics:{scope:rows.length,inserts:0,deactivations:0,outsideScopeChanges:0,predictedProductUpdates:rows.filter(row=>row.price!==row.originalPrice||row.stock!==row.originalStock).length,predictedErpRecords:rows.length,predictedErpSemanticUpdates,price2Positive,price2Zero,priceWouldChange,priceUnchanged,over50PercentChanges,zeroPriceRegressions,stockWouldChange,stockUnchanged,positiveToZero,zeroToPositive,resultingStockZero,stockFormulaMismatches}}}
async function loadScope(db:ExtendedPrismaClient|ExtendedTransactionClient,allowlist:FifthWaveAllowlist){return db.product.findMany({where:{id:{in:allowlist.entries.map(x=>x.productId)}},select:{id:true,externalId:true,sku:true,price:true,stock:true,isDeleted:true,isActive:true}}) as unknown as Promise<FifthWaveScopeProduct[]>}
export async function prepareFifthWavePlan(db:ExtendedPrismaClient,allowlist:FifthWaveAllowlist,feed:ErpProduct[],phase:'preview-before-backfill'|'post-backfill'):Promise<FifthWavePlan>{const[scope,extra]=await Promise.all([loadScope(db,allowlist),getErpExtraData(db)]);return buildFifthWavePlan(allowlist,feed,scope,extra,phase)}
function updateSql(count:number){const values=Array.from({length:count},(_,i)=>`($${i*5+1},$${i*5+2},$${i*5+3},$${i*5+4}::numeric,$${i*5+5}::int)`).join(',');return`UPDATE "Product" p SET price=v.price,stock=v.stock,"lastSyncRunId"=$${count*5+1},"updatedAt"=now() FROM (VALUES ${values}) v(id,"externalId",sku,price,stock) WHERE p.id=v.id AND p."externalId"=v."externalId" AND p.sku=v.sku AND p."isDeleted"=false`}
export async function executeFifthWaveSync(db:ExtendedPrismaClient,allowlist:FifthWaveAllowlist,feed:ErpProduct[],xmlSha:string,allowlistSha:string):Promise<{runId:string;updated:number;metrics:FifthWavePlan['metrics'];durationMs:number;inserted:number;deactivated:number;rollback:boolean}>{const startedAt=new Date(),runId=randomUUID();const result=await db.$transaction(async tx=>{const scope=await loadScope(tx,allowlist),stored=await tx.keyValueSetting.findUnique({where:{key:'erp-extra-data'}}),current=stored?.value&&typeof stored.value==='object'&&!Array.isArray(stored.value)?stored.value as unknown as Record<string,ErpExtraData>:{},plan=buildFifthWavePlan(allowlist,feed,scope,current,'post-backfill'),params:unknown[]=plan.rows.flatMap(row=>[row.id,row.externalId,row.productSku,row.price,row.stock]);params.push(runId);const updated=await tx.$executeRawUnsafe(updateSql(plan.rows.length),...params);if(updated!==FIFTH_WAVE_SIZE)throw new Error(`ATOMIC_UPDATE_COUNT_MISMATCH:${updated}`);await tx.keyValueSetting.upsert({where:{key:'erp-extra-data'},create:{key:'erp-extra-data',value:plan.extraData as unknown as Prisma.InputJsonValue},update:{value:plan.extraData as unknown as Prisma.InputJsonValue}});await tx.syncRun.create({data:{id:runId,status:'completed',triggeredBy:`controlled-fifth-wave-normalized-sku:${xmlSha}:${allowlistSha}`,startedAt,finishedAt:new Date(),productsTotal:FIFTH_WAVE_SIZE,productsSynced:updated,deactivated:0,errorCount:0}});return{runId,updated,metrics:plan.metrics}},{isolationLevel:'Serializable',timeout:120_000,maxWait:10_000});return{...result,durationMs:Date.now()-startedAt.getTime(),inserted:0,deactivated:0,rollback:false}}
