import { randomUUID } from 'node:crypto'
import type { Prisma } from '@/generated/prisma/client'
import type { ExtendedPrismaClient, ExtendedTransactionClient } from '../prisma'
import { getErpExtraData, type ErpExtraData } from './erp-extra-data-store'
import { selectedStock } from './sync-rules'
import { parseXml, type Allowlist } from './final-existing-backfill'

type ScopeProduct={id:string;externalId:string|null;sku:string|null;price:unknown;stock:number;isActive:boolean;isDeleted:boolean}
export type FinalExistingPlan={rows:Array<{id:string;externalId:string;sku:string|null;price:number;stock:number;originalPrice:number;originalStock:number}>;extraData:Record<string,ErpExtraData>;metrics:{scope:number;predictedProductUpdates:number;predictedErpSemanticUpdates:number;priceUpdates:number;priceUnchanged:number;stockUpdates:number;stockUnchanged:number;zeroTierPreserved:number;zeroPriceRegressions:number;stockFormulaMismatches:number;conflicts:number}}

async function loadScope(db:ExtendedPrismaClient|ExtendedTransactionClient,a:Allowlist){return db.product.findMany({where:{id:{in:a.entries.map(e=>e.productId)}},select:{id:true,externalId:true,sku:true,price:true,stock:true,isActive:true,isDeleted:true}}) as unknown as Promise<ScopeProduct[]>}

export function buildFinalExistingPlan(a:Allowlist,xml:string,products:ScopeProduct[],current:Record<string,ErpExtraData>):FinalExistingPlan{
  if(products.length!==8)throw new Error(`FINAL_EXISTING_SCOPE_SIZE:${products.length}`)
  const parsed=parseXml(xml),counts=new Map<string,number>();for(const x of parsed)counts.set(x.sku,(counts.get(x.sku)??0)+1)
  const feed=new Map(parsed.map(x=>[x.sku,x])),byId=new Map(products.map(p=>[p.id,p])),extraData={...current},rows:FinalExistingPlan['rows']=[]
  let predictedErpSemanticUpdates=0,priceUpdates=0,priceUnchanged=0,stockUpdates=0,stockUnchanged=0,zeroTierPreserved=0,zeroPriceRegressions=0,stockFormulaMismatches=0
  for(const e of a.entries){const p=byId.get(e.productId),x=feed.get(e.xmlSku);if(!p||!x||counts.get(e.xmlSku)!==1||p.externalId!==e.xmlSku||p.sku!==e.currentLocalSku||p.isDeleted||p.isActive!==e.expectedActive)throw new Error(`FINAL_EXISTING_IMMUTABLE_SCOPE:${e.productId}`);const originalPrice=Number(p.price),price=x.price2>0?x.price2:originalPrice,stock=selectedStock(x.warehouseQuantities);if(x.price2===0)zeroTierPreserved++;if(price===originalPrice)priceUnchanged++;else priceUpdates++;if(stock===p.stock)stockUnchanged++;else stockUpdates++;if(originalPrice>0&&price===0)zeroPriceRegressions++;if(stock!==[10000,10001,10002,10005].reduce((n,id)=>n+Math.max(0,x.warehouseQuantities[String(id)]??0),0))stockFormulaMismatches++;rows.push({id:p.id,externalId:e.xmlSku,sku:p.sku,price,stock,originalPrice,originalStock:p.stock});const next:ErpExtraData={prices:{price1:x.prices.price1,price2:x.prices.price2,price3:x.prices.price3,price4:x.prices.price4},warehouseQuantities:x.warehouseQuantities};if(JSON.stringify(current[e.xmlSku])!==JSON.stringify(next))predictedErpSemanticUpdates++;extraData[e.xmlSku]=next}
  if(rows.length!==8||zeroPriceRegressions||stockFormulaMismatches)throw new Error('FINAL_EXISTING_PLAN_GATE_FAILED')
  return{rows,extraData,metrics:{scope:8,predictedProductUpdates:rows.filter(r=>r.price!==r.originalPrice||r.stock!==r.originalStock).length,predictedErpSemanticUpdates,priceUpdates,priceUnchanged,stockUpdates,stockUnchanged,zeroTierPreserved,zeroPriceRegressions,stockFormulaMismatches,conflicts:0}}
}

export async function prepareFinalExistingPlan(db:ExtendedPrismaClient,a:Allowlist,xml:string):Promise<FinalExistingPlan>{const[scope,extra]=await Promise.all([loadScope(db,a),getErpExtraData(db)]);return buildFinalExistingPlan(a,xml,scope,extra)}
function updateSql(count:number){const values=Array.from({length:count},(_,i)=>`($${i*5+1},$${i*5+2},$${i*5+3},$${i*5+4}::numeric,$${i*5+5}::int)`).join(',');return`UPDATE "Product" p SET price=v.price,stock=v.stock,"lastSyncRunId"=$${count*5+1},"updatedAt"=now() FROM (VALUES ${values}) v(id,"externalId",sku,price,stock) WHERE p.id=v.id AND p."externalId"=v."externalId" AND p.sku IS NOT DISTINCT FROM v.sku AND p."isDeleted"=false`}
export async function executeFinalExistingSync(db:ExtendedPrismaClient,a:Allowlist,xml:string,xmlSha:string,allowlistSha:string):Promise<{runId:string;updated:number;metrics:FinalExistingPlan['metrics'];durationMs:number;inserted:number;deactivated:number;rollback:boolean}>{const startedAt=new Date(),runId=randomUUID();const result=await db.$transaction(async tx=>{const scope=await loadScope(tx,a),stored=await tx.keyValueSetting.findUnique({where:{key:'erp-extra-data'}}),current=stored?.value&&typeof stored.value==='object'&&!Array.isArray(stored.value)?stored.value as unknown as Record<string,ErpExtraData>:{},plan=buildFinalExistingPlan(a,xml,scope,current),params:unknown[]=plan.rows.flatMap(r=>[r.id,r.externalId,r.sku,r.price,r.stock]);params.push(runId);const updated=await tx.$executeRawUnsafe(updateSql(8),...params);if(updated!==8)throw new Error(`FINAL_EXISTING_ATOMIC_UPDATE_COUNT:${updated}`);await tx.keyValueSetting.upsert({where:{key:'erp-extra-data'},create:{key:'erp-extra-data',value:plan.extraData as unknown as Prisma.InputJsonValue},update:{value:plan.extraData as unknown as Prisma.InputJsonValue}});await tx.syncRun.create({data:{id:runId,status:'completed',triggeredBy:`controlled-final-existing:${xmlSha}:${allowlistSha}`,startedAt,finishedAt:new Date(),productsTotal:8,productsSynced:8,deactivated:0,errorCount:0}});return{runId,updated,metrics:plan.metrics}},{isolationLevel:'Serializable',timeout:120000,maxWait:10000});return{...result,durationMs:Date.now()-startedAt.getTime(),inserted:0,deactivated:0,rollback:false}}
