import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { applyFifthWaveAtomic, assertFifthWaveBaseline, FIFTH_WAVE_ALLOWLIST_SHA256, FIFTH_WAVE_DEFERRED_SKUS, FIFTH_WAVE_EXCLUDED_PRODUCT_IDS, FIFTH_WAVE_SIZE, fifthWaveSha256, validateFifthWave, type FifthWaveAllowlist, type FifthWaveProduct } from './fifth-wave-backfill'
import { buildFifthWavePlan, type FifthWaveScopeProduct } from './controlled-fifth-wave'
import type { ErpProduct } from './erp-adapter'
const content=readFileSync('fifth-wave-normalized-sku-allowlist.json'),allowlist=JSON.parse(content.toString()) as FifthWaveAllowlist
const escapeXml=(value:string)=>value.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')
const xml=`<root>${allowlist.entries.map(entry=>`<item><sku>${escapeXml(entry.xmlSku)}</sku><code>${escapeXml(entry.xmlEan??'')}</code><title>${escapeXml(entry.xmlName)}</title></item>`).join('')}</root>`,xmlPolicy={xmlSha256:fifthWaveSha256(xml)}
const products=():FifthWaveProduct[]=>allowlist.entries.map(entry=>({id:entry.productId,sku:entry.productSku,externalId:null,barcode:entry.productBarcode,isDeleted:false}))
const mutate=(change:(value:FifthWaveAllowlist)=>void)=>{const value=structuredClone(allowlist);change(value);const data=Buffer.from(JSON.stringify(value));return{data,policy:{allowlistSha256:fifthWaveSha256(data)}}}
describe('fifth-wave immutable normalized-SKU gates',()=>{
  it('binds the expected immutable allowlist hash',()=>expect(fifthWaveSha256(content)).toBe(FIFTH_WAVE_ALLOWLIST_SHA256))
  it('accepts exactly 24 identities',()=>expect(validateFifthWave(content,xml,products(),'pre-backfill',xmlPolicy).entries).toHaveLength(24))
  it('rejects allowlist SHA mismatch',()=>expect(()=>validateFifthWave(Buffer.concat([content,Buffer.from(' ')]),xml,products(),'pre-backfill',xmlPolicy)).toThrow('ALLOWLIST_SHA_MISMATCH'))
  it('rejects XML SHA mismatch',()=>expect(()=>validateFifthWave(content,`${xml} `,products(),'pre-backfill',xmlPolicy)).toThrow('XML_SHA_MISMATCH'))
  it('rejects baseline fingerprint mismatch',()=>expect(()=>assertFifthWaveBaseline({count:6378,externalIdCount:3526,active:2229,inactive:4149,syncRunCount:6,fingerprint:'drift'})).toThrow('BASELINE_MISMATCH'))
  it('rejects missing Product',()=>expect(()=>validateFifthWave(content,xml,products().slice(1),'pre-backfill',xmlPolicy)).toThrow('missing Product'))
  it('rejects Product SKU drift',()=>{const rows=products();rows[0].sku='drift';expect(()=>validateFifthWave(content,xml,rows,'pre-backfill',xmlPolicy)).toThrow('Product SKU drift')})
  it('rejects XML SKU drift',()=>{const changed=mutate(value=>{value.entries[0].xmlSku='drift';value.entries[0].externalIdToSet='drift'});expect(()=>validateFifthWave(changed.data,xml,products(),'pre-backfill',{...changed.policy,...xmlPolicy})).toThrow('normalization identity drift')})
  it('rejects filled externalId',()=>{const rows=products();rows[0].externalId='claimed';expect(()=>validateFifthWave(content,xml,rows,'pre-backfill',xmlPolicy)).toThrow('externalId gate failed')})
  it('rejects competing externalId claimant',()=>{const rows=products();rows.push({id:'claimant',sku:'other',externalId:allowlist.entries[0].xmlSku,barcode:null,isDeleted:false});expect(()=>validateFifthWave(content,xml,rows,'pre-backfill',xmlPolicy)).toThrow('XML SKU already claimed')})
  it('rejects normalized-key collision',()=>{const entry=allowlist.entries[0],rows=products();rows.push({id:'collision',sku:`0${entry.productSku}`,externalId:null,barcode:null,isDeleted:false});expect(()=>validateFifthWave(content,xml,rows,'pre-backfill',xmlPolicy)).toThrow('normalized key collision')})
  it('rejects wrong normalization type',()=>{const changed=mutate(value=>{value.entries[0].normalizationType='DOT_NORMALIZATION'});expect(()=>validateFifthWave(changed.data,xml,products(),'pre-backfill',{...changed.policy,...xmlPolicy})).toThrow('normalization identity drift')})
  it('rejects multiple transformations',()=>{const changed=mutate(value=>{value.entries[0].productSku='00 123';value.entries[0].xmlSku='123';value.entries[0].externalIdToSet='123'}),rows=products();rows[0].sku='00 123';expect(()=>validateFifthWave(changed.data,xml,rows,'pre-backfill',{...changed.policy,...xmlPolicy})).toThrow('normalization identity drift')})
  it('hard-excludes manual/rejected/already-resolved Product IDs',()=>expect(allowlist.entries.some(entry=>FIFTH_WAVE_EXCLUDED_PRODUCT_IDS.has(entry.productId))).toBe(false))
  it('hard-excludes deferred SKUs',()=>expect(allowlist.entries.some(entry=>FIFTH_WAVE_DEFERRED_SKUS.has(entry.xmlSku.toLocaleUpperCase('en-US')))).toBe(false))
  it('rejects soft-deleted Product',()=>{const rows=products();rows[0].isDeleted=true;expect(()=>validateFifthWave(content,xml,rows,'pre-backfill',xmlPolicy)).toThrow('soft-deleted Product')})
})
function atomicStore(affected=FIFTH_WAVE_SIZE){const state=new Map(products().map(p=>[p.id,{...p}]));return{state,store:{transaction:async<T>(operation:(tx:{loadAll:()=>Promise<FifthWaveProduct[]>;updateExternalIds:(entries:FifthWaveAllowlist['entries'])=>Promise<number>})=>Promise<T>)=>{const draft=new Map([...state].map(([id,p])=>[id,{...p}]));const result=await operation({loadAll:async()=>[...draft.values()],updateExternalIds:async entries=>{for(const entry of entries.slice(0,affected)){const p=draft.get(entry.productId);if(p)p.externalId=entry.externalIdToSet}return affected}});state.clear();for(const[id,p]of draft)state.set(id,p);return result}}}}
describe('fifth-wave atomic contract',()=>{it('rejects partial affected-row update',async()=>{const{store}=atomicStore(23);await expect(applyFifthWaveAtomic(store,content,xml,xmlPolicy)).rejects.toThrow('ATOMIC_UPDATE_COUNT_MISMATCH:23')});it('changes only scoped externalId',async()=>{const{store,state}=atomicStore();await applyFifthWaveAtomic(store,content,xml,xmlPolicy);expect(allowlist.entries.every(entry=>state.get(entry.productId)?.externalId===entry.externalIdToSet&&state.get(entry.productId)?.sku===entry.productSku)).toBe(true)})})
const scope=():FifthWaveScopeProduct[]=>allowlist.entries.map(entry=>({id:entry.productId,externalId:null,sku:entry.productSku,price:10,stock:5,isDeleted:false,isActive:true}))
const feed=():ErpProduct[]=>allowlist.entries.map((entry,index)=>({externalId:entry.xmlSku,title:entry.xmlSku,price:index===0?0:12,stock:6,prices:{price1:99,price2:index===0?0:12,price3:88,price4:77},warehouseQuantities:{'10000':1,'10001':2,'10002':3,'10003':100,'10005':0}}))
describe('fifth-wave controlled preview',()=>{it('preserves price2 zero and has no fallback',()=>{const plan=buildFifthWavePlan(allowlist,feed(),scope(),{},'preview-before-backfill');expect(plan.rows[0].price).toBe(10);expect(plan.metrics.zeroPriceRegressions).toBe(0)});it('uses exactly four stock warehouses',()=>expect(buildFifthWavePlan(allowlist,feed(),scope(),{},'preview-before-backfill').rows[0].stock).toBe(6));it('makes insert, deactivation and outside-scope mutation impossible',()=>expect(buildFifthWavePlan(allowlist,feed(),scope(),{},'preview-before-backfill').metrics).toMatchObject({scope:24,inserts:0,deactivations:0,outsideScopeChanges:0}))})
