import { createHash } from 'node:crypto'
import { XMLParser } from 'fast-xml-parser'
import { selectedStock } from './sync-rules'
import { GRINS_WAREHOUSE_INDEX_TO_ID } from './grins-warehouse-map'

export const FINAL_EXISTING_XML_SHA='26c001368c79f9cfb9100d1cf67c0a0c479fe181f11e0b15c5944888f6517cad'
export const FINAL_EXISTING_ALLOWLIST_SHA='fbcb6e7d3940b4f92127b1c07d53963682a7abf34f3d63cb1eccf46c0b7a0337'
export const FINAL_EXISTING_BASELINE={productCount:17422,externalIdCount:14624,unlinkedCount:2798,active:2229,inactive:15193,syncRunCount:10,duplicateExternalId:0,fingerprint:'44a1637730da00f90ff5eb4287349739'} as const
export const FINAL_EXISTING_TARGETS=new Map([['21420','7637BR'],['21283','81580138'],['21623','E3570301'],['21624','E3565700'],['19015','NHK3212'],['19018','NHK4211'],['21352','AC-879'],['22129','1010250041']])
export const PERMANENT_EXCLUSION={productId:'13324',xmlSku:'97388150',reason:'PROTECTED_AMBIGUOUS_DEFERRED_INTERSECTION'} as const
export type State={productCount:number;externalIdCount:number;unlinkedCount:number;active:number;inactive:number;syncRunCount:number;duplicateExternalId:number;fingerprint:string}
export type ProductIdentity={id:string;externalId:string|null;sku:string|null;barcode:string|null;title:string;titleEn:string|null;titleLv:string|null;brand:string;category:string;description:string|null;image:string|null;images:string[];price:unknown;stock:number;isActive:boolean;isDeleted:boolean;createdAt:Date;updatedAt:Date;lastSyncRunId:string|null}
export type Entry={productId:string;currentLocalSku:string|null;currentBarcode:string|null;localTitle:string;xmlSku:string;xmlEan:string;xmlTitle:string;externalIdToSet:string;matchType:'UNIQUE_EXACT_EAN';identityEvidence:string[];expectedActive:boolean;baselineProtected:Omit<ProductIdentity,'externalId'>}
export type Allowlist={schemaVersion:1;wave:'final-existing-product-backfill';executable:true;entryCount:number;baseline:typeof FINAL_EXISTING_BASELINE;xmlSha256:string;permanentExclusion:typeof PERMANENT_EXCLUSION;entries:Entry[]}
type XmlRow={sku:string;ean:string;title:string;price2:number;prices:Record<string,number>;warehouseQuantities:Record<string,number>}
const parser=new XMLParser({ignoreAttributes:false,attributeNamePrefix:'@_',parseTagValue:false,processEntities:false,isArray:n=>n==='item'||n==='warehouse'})
export const hash=(value:string|Buffer)=>createHash('sha256').update(value).digest('hex')
export function parseXml(xml:string):XmlRow[]{return (((parser.parse(xml) as any).root?.item??[]) as any[]).map(x=>{const warehouseQuantities:Record<string,number>={};for(const w of x.warehouses?.warehouse??[]){const id=GRINS_WAREHOUSE_INDEX_TO_ID[Number(w['@_id'])-1];if(id)warehouseQuantities[id]=Number(w['#text']??0)}return{sku:String(x.sku??'').trim(),ean:String(x.code??'').trim(),title:String(x.title??'').trim(),price2:Number(x.price2??0),prices:{price1:Number(x.price1??0),price2:Number(x.price2??0),price3:Number(x.price3??0),price4:Number(x.price4??0)},warehouseQuantities}})}
export function assertBaseline(value:State):void{for(const [key,expected] of Object.entries(FINAL_EXISTING_BASELINE))if(value[key as keyof State]!==expected)throw new Error(`FINAL_EXISTING_BASELINE_DRIFT:${JSON.stringify(value)}`)}
export function parseAllowlist(content:string|Buffer,expectedSha=FINAL_EXISTING_ALLOWLIST_SHA):Allowlist{if(expectedSha==='TO_BE_BOUND'||hash(content)!==expectedSha)throw new Error('FINAL_EXISTING_ALLOWLIST_SHA_MISMATCH');const a=JSON.parse(content.toString()) as Allowlist;if(!a.executable||a.wave!=='final-existing-product-backfill'||a.entryCount!==a.entries.length||!a.entries.length)throw new Error('FINAL_EXISTING_ALLOWLIST_METADATA');if(a.xmlSha256!==FINAL_EXISTING_XML_SHA||JSON.stringify(a.baseline)!==JSON.stringify(FINAL_EXISTING_BASELINE))throw new Error('FINAL_EXISTING_BINDING_MISMATCH');if(JSON.stringify(a.permanentExclusion)!==JSON.stringify(PERMANENT_EXCLUSION))throw new Error('FINAL_EXISTING_EXCLUSION_MISMATCH');return a}
const protectedSnapshot=(p:ProductIdentity):Omit<ProductIdentity,'externalId'>=>{const {externalId:_,...rest}=p;void _;return rest}
export function validateScope(a:Allowlist,xml:string,products:ProductIdentity[],protectedSkus:Set<string>,phase:'pre'|'post'='pre'):{conflicts:number;skipped:number}{if(hash(xml)!==FINAL_EXISTING_XML_SHA)throw new Error('FINAL_EXISTING_XML_SHA_MISMATCH');if(a.entries.some(e=>e.productId===PERMANENT_EXCLUSION.productId||e.xmlSku===PERMANENT_EXCLUSION.xmlSku))throw new Error('PROTECTED_97388150_INTERSECTION');const errors:string[]=[],rows=parseXml(xml),byId=new Map(products.map(p=>[p.id,p])),external=new Map(products.filter(p=>p.externalId).map(p=>[p.externalId!,p])),sku=new Map<string,ProductIdentity[]>(),ean=new Map<string,ProductIdentity[]>();for(const p of products){if(p.sku)sku.set(p.sku,[...(sku.get(p.sku)??[]),p]);if(p.barcode)ean.set(p.barcode,[...(ean.get(p.barcode)??[]),p])}for(const values of [a.entries.map(e=>e.productId),a.entries.map(e=>e.xmlSku),a.entries.map(e=>e.externalIdToSet)])if(new Set(values).size!==a.entries.length)errors.push('duplicate target');for(const e of a.entries){const p=byId.get(e.productId),x=rows.filter(r=>r.sku===e.xmlSku);if(!p){errors.push(`missing ${e.productId}`);continue}if(protectedSkus.has(e.xmlSku))errors.push(`protected intersection ${e.xmlSku}`);if(p.isDeleted||p.externalId!==(phase==='pre'?null:e.xmlSku))errors.push(`Product state ${e.productId}`);if(x.length!==1||x[0].ean!==e.xmlEan||e.externalIdToSet!==e.xmlSku)errors.push(`XML identity ${e.xmlSku}`);if(external.has(e.xmlSku)&&external.get(e.xmlSku)?.id!==p.id)errors.push(`occupied externalId ${e.xmlSku}`);if(p.sku&&((sku.get(p.sku)?.length??0)!==1||p.sku!==e.currentLocalSku))errors.push(`competing SKU ${e.productId}`);if(!p.barcode||p.barcode!==e.xmlEan||(ean.get(e.xmlEan)?.length??0)!==1)errors.push(`competing EAN ${e.productId}`);if(JSON.stringify(protectedSnapshot(p))!==JSON.stringify(e.baselineProtected))errors.push(`protected-field drift ${e.productId}`)}if(errors.length)throw new Error(`FINAL_EXISTING_SCOPE_INVALID:\n${errors.join('\n')}`);return{conflicts:0,skipped:0}}
export function previewSync(a:Allowlist,xml:string,products:ProductIdentity[]){const feed=new Map(parseXml(xml).map(x=>[x.sku,x])),byId=new Map(products.map(p=>[p.id,p]));let price2Positive=0,price2Zero=0,priceChanged=0,priceUnchanged=0,zeroTierPreserved=0,over50PercentChanges=0,largeAbsoluteChanges=0,zeroPriceRegressions=0,stockChanged=0,stockUnchanged=0,positiveToZero=0,zeroToPositive=0,resultingStockZero=0,formulaMismatches=0;const rows=a.entries.map(e=>{const p=byId.get(e.productId),x=feed.get(e.xmlSku);if(!p||!x)throw new Error('FINAL_EXISTING_PREVIEW_SCOPE_DRIFT');const oldPrice=Number(p.price),price=x.price2>0?x.price2:oldPrice,stock=selectedStock(x.warehouseQuantities);if(x.price2>0)price2Positive++;else{price2Zero++;zeroTierPreserved++}if(price===oldPrice)priceUnchanged++;else priceChanged++;if(oldPrice>0&&Math.abs(price-oldPrice)/oldPrice>.5)over50PercentChanges++;if(Math.abs(price-oldPrice)>=50)largeAbsoluteChanges++;if(oldPrice>0&&price===0)zeroPriceRegressions++;if(stock===p.stock)stockUnchanged++;else stockChanged++;if(p.stock>0&&stock===0)positiveToZero++;if(p.stock===0&&stock>0)zeroToPositive++;if(stock===0)resultingStockZero++;if(stock!==selectedStock(x.warehouseQuantities))formulaMismatches++;return{productId:p.id,xmlSku:e.xmlSku,currentPrice:oldPrice,resultingPrice:price,currentStock:p.stock,resultingStock:stock,isActiveUnchanged:p.isActive,prices:x.prices,warehouseQuantities:x.warehouseQuantities}});return{rows,metrics:{scope:rows.length,price2Positive,price2Zero,priceChanged,priceUnchanged,zeroTierPreserved,over50PercentChanges,largeAbsoluteChanges,zeroPriceRegressions,stockChanged,stockUnchanged,positiveToZero,zeroToPositive,resultingStockZero,formulaMismatches,predictedErpRecords:rows.length,databaseWrites:0}}}
export type AtomicStore={transaction:<T>(fn:(tx:{loadAll:()=>Promise<ProductIdentity[]>;updateExternalIds:(entries:Entry[])=>Promise<number>})=>Promise<T>)=>Promise<T>}
export async function applyAtomic(store:AtomicStore,a:Allowlist,xml:string,protectedSkus:Set<string>){return store.transaction(async tx=>{validateScope(a,xml,await tx.loadAll(),protectedSkus);const n=await tx.updateExternalIds(a.entries);if(n!==a.entries.length)throw new Error(`FINAL_EXISTING_AFFECTED_ROWS:${n}`);return n})}
