import { createHash } from 'node:crypto'
import { readFile, writeFile } from 'node:fs/promises'
import { config } from 'dotenv'
import { XMLParser } from 'fast-xml-parser'
import { GRINS_WAREHOUSE_INDEX_TO_ID } from '../lib/sync/grins-warehouse-map'

config({ path: '.env.local' })

const EXPECTED = { productCount:8577, externalIdCount:5779, unlinkedCount:2798, active:2229, inactive:6348, syncRunCount:9, fingerprint:'c9eaa51facfe0b6c60ab45bf5589e566', xmlCount:16176, xmlSha:'26c001368c79f9cfb9100d1cf67c0a0c479fe181f11e0b15c5944888f6517cad' }
const AMBIGUOUS = new Set(['24006256','97388150','BA02','DKIRI','KJMN0352','NIA308001','NIA407001','SS-40/3'])
const CASE_REVIEW = new Set(['K18','K86'])
const REJECTED = new Map([['001','1'],['010','10'],['016100','16100'],['016112','16112'],['005','5'],['5.5','55'],['3.4','34'],['0013','13'],['DR420','DR4.20']])
const MANUAL_PRODUCT_ID = '20469'
const MANUAL_XML_SKU = '67286'
const ALLOWED_WAREHOUSES = ['10000','10001','10002','10005']

type Warehouse = {'@_id':string;'#text'?:string}
type RawXml = {sku?:string;code?:string;title?:string;price2?:string;warehouses?:{warehouse?:Warehouse[]}}
type XmlRow = {sku:string;ean:string;name:string;price2:number;allowedStock:number}
type Product = {id:string;sku:string|null;externalId:string|null;barcode:string|null;title:string;titleEn:string|null;titleLv:string|null;brand:string;category:string;specVolume:string|null;specType:string|null;price:unknown;stock:number;isActive:boolean;isDeleted:boolean}
type LocalClass = 'EXACT_IDENTITY'|'NORMALIZED_IDENTITY'|'EAN_IDENTITY'|'COMPOUND_STRONG'|'POSSIBLE_MATCH'|'MANUAL_REVIEW'|'REJECTED_MATCH'|'LOCAL_ONLY'

const s=(v:unknown)=>String(v??'').trim()
const upper=(v:unknown)=>s(v).toLocaleUpperCase('en-US')
const eanKey=(v:unknown)=>upper(v).replace(/[\s-]+/gu,'')
const nameKey=(v:unknown)=>s(v).normalize('NFKC').toLocaleLowerCase('en-US').replace(/[^\p{L}\p{N}]+/gu,' ').trim().replace(/\s+/gu,' ')
const tokens=(v:unknown)=>[...new Set(nameKey(v).split(' ').filter(x=>x.length>1))]
const dice=(a:unknown,b:unknown)=>{const aa=new Set(tokens(a)),bb=new Set(tokens(b));if(!aa.size||!bb.size)return 0;let n=0;for(const x of aa)if(bb.has(x))n++;return 2*n/(aa.size+bb.size)}
const sha=(v:string|Buffer)=>createHash('sha256').update(v).digest('hex')
const num=(v:unknown)=>{const n=Number(v??0);return Number.isFinite(n)?n:0}
const csv=(rows:Record<string,unknown>[])=>{const columns=[...new Set(rows.flatMap(Object.keys))];const q=(v:unknown)=>`"${String(v??'').replace(/"/g,'""')}"`;return '\ufeff'+(columns.length?[columns.map(q).join(','),...rows.map(r=>columns.map(c=>q(r[c])).join(','))].join('\n')+'\n':'')}
const index=<T>(rows:T[],key:(row:T)=>string)=>{const out=new Map<string,T[]>();for(const row of rows){const k=key(row);if(k)out.set(k,[...(out.get(k)??[]),row])}return out}
const controlledRelations=(sku:string)=>[
  ['CASE_ONLY',sku.toLocaleLowerCase('en-US')],
  ['LEADING_ZERO',sku.replace(/^0+(?=\d)/u,'')],
  ['DOT_NORMALIZATION',sku.replace(/\./gu,'')],
  ['INTERNAL_SPACE_NORMALIZATION',sku.replace(/[\s\u00a0]+/gu,'')],
] as const

async function main(){
  const { prisma } = await import('../lib/prisma')
  const state=async()=>(await prisma.$queryRawUnsafe<Array<Record<string,number|string>>>(`SELECT COUNT(*)::int "productCount",COUNT("externalId")::int "externalIdCount",COUNT(*) FILTER(WHERE "externalId" IS NULL)::int "unlinkedCount",COUNT(*) FILTER(WHERE "isActive")::int active,COUNT(*) FILTER(WHERE NOT "isActive")::int inactive,(SELECT COUNT(*)::int FROM "SyncRun") "syncRunCount",md5(COALESCE(string_agg(row_to_json(p)::text,'' ORDER BY p.id),'')) fingerprint FROM "Product" p`))[0]
  try{
    const before=await state(),xmlText=await readFile('export.xml','utf8'),xmlSha=sha(xmlText)
    const raw=((new XMLParser({ignoreAttributes:false,attributeNamePrefix:'@_',parseTagValue:false,processEntities:false,isArray:n=>n==='item'||n==='warehouse'}).parse(xmlText) as {root?:{item?:RawXml[]}}).root?.item??[])
    if(Object.entries(EXPECTED).some(([k,v])=>k!=='xmlCount'&&k!=='xmlSha'&&before[k]!==v)||raw.length!==EXPECTED.xmlCount||xmlSha!==EXPECTED.xmlSha)throw new Error(`BASELINE_DRIFT:${JSON.stringify({before,xmlCount:raw.length,xmlSha})}`)
    const xml:XmlRow[]=raw.map(x=>{const wh:Record<string,number>={};for(const w of x.warehouses?.warehouse??[]){const id=GRINS_WAREHOUSE_INDEX_TO_ID[Number(w['@_id'])-1];if(id)wh[id]=num(w['#text'])}return{sku:s(x.sku),ean:s(x.code),name:s(x.title),price2:num(x.price2),allowedStock:ALLOWED_WAREHOUSES.reduce((n,id)=>n+Math.max(0,wh[id]??0),0)}})
    const products=await prisma.product.findMany({select:{id:true,sku:true,externalId:true,barcode:true,title:true,titleEn:true,titleLv:true,brand:true,category:true,specVolume:true,specType:true,price:true,stock:true,isActive:true,isDeleted:true}}) as Product[]
    const linked=products.filter(p=>p.externalId),unlinked=products.filter(p=>!p.externalId),linkedSkus=new Set(linked.map(p=>s(p.externalId))),freeXml=xml.filter(x=>!linkedSkus.has(x.sku))
    const xmlSku=index(xml,x=>x.sku),freeSku=index(freeXml,x=>x.sku),freeEan=index(freeXml,x=>x.ean),allEan=index(xml,x=>x.ean),productEan=index(products,p=>s(p.barcode)),productNormalizedEan=index(products,p=>eanKey(p.barcode)),unlinkedSku=index(unlinked,p=>s(p.sku)),productSku=index(products,p=>s(p.sku))
    const normIndexes=new Map<string,Map<string,XmlRow[]>>();for(const [rule] of controlledRelations('x'))normIndexes.set(rule,new Map());for(const x of freeXml)for(const [rule,key] of controlledRelations(x.sku)){const m=normIndexes.get(rule)!;m.set(key,[...(m.get(key)??[]),x])}
    const freeName=index(freeXml,x=>nameKey(x.name)),freeToken=new Map<string,XmlRow[]>(),allProductName=new Map<string,Product[]>(),productNormIndexes=new Map<string,Map<string,Product[]>>();for(const [rule] of controlledRelations('x'))productNormIndexes.set(rule,new Map());for(const x of freeXml)for(const token of tokens(x.name))freeToken.set(token,[...(freeToken.get(token)??[]),x]);for(const p of products){for(const n of [p.title,p.titleEn,p.titleLv]){const k=nameKey(n);if(k)allProductName.set(k,[...(allProductName.get(k)??[]),p])}const ps=s(p.sku);if(ps)for(const [rule,key] of controlledRelations(ps)){const m=productNormIndexes.get(rule)!;m.set(key,[...(m.get(key)??[]),p])}}
    const blockedXml=new Set<string>(),localRows:Record<string,unknown>[]=[]
    for(const p of unlinked){
      const sku=s(p.sku),ean=s(p.barcode),names=[p.title,p.titleEn,p.titleLv].filter(Boolean),brandKey=nameKey(p.brand);let classification:LocalClass='LOCAL_ONLY',evidence='No reasonable XML candidate',candidate:XmlRow|undefined,confidence='none'
      if(p.id===MANUAL_PRODUCT_ID){classification='MANUAL_REVIEW';candidate=freeSku.get(MANUAL_XML_SKU)?.[0];evidence='Known 067286 → 67286 case; local brand FUDGE conflicts with identity and may be historical data error';confidence='manual-only'}
      else if(AMBIGUOUS.has(upper(sku))){classification='MANUAL_REVIEW';candidate=freeSku.get(sku)?.[0];evidence='Known ambiguous duplicate SKU; multiple local identity claimants';confidence='ambiguous'}
      else if(CASE_REVIEW.has(upper(sku))){classification='MANUAL_REVIEW';candidate=freeXml.find(x=>upper(x.sku)===upper(sku));evidence='Known case-review scope; deliberately deferred';confidence='manual-only'}
      else if(REJECTED.has(sku)){classification='REJECTED_MATCH';candidate=freeSku.get(REJECTED.get(sku)!)?.[0];evidence=`Known rejected normalization ${sku} → ${REJECTED.get(sku)}; identity contradiction retained`;confidence='rejected'}
      else {
        const exact=sku?freeSku.get(sku)??[]:[]
        if(exact.length===1&&(xmlSku.get(sku)?.length===1)&&(unlinkedSku.get(sku)?.length===1)&&(productSku.get(sku)?.length===1)){classification='EXACT_IDENTITY';candidate=exact[0];evidence='Globally unique exact SKU';confidence='strong'}
        if(!candidate&&sku){const hits=new Map<string,{x:XmlRow;rule:string}>();for(const [rule,key] of controlledRelations(sku))for(const x of normIndexes.get(rule)?.get(key)??[])if(x.sku!==sku)hits.set(x.sku,{x,rule});if(hits.size===1){const hit=[...hits.values()][0];candidate=hit.x;classification='NORMALIZED_IDENTITY';evidence=`Unique controlled ${hit.rule} SKU relation`;confidence='strong-candidate'}}
        if(!candidate&&ean){const hits=freeEan.get(ean)??[];if(hits.length===1&&(allEan.get(ean)?.length===1)&&(productEan.get(ean)?.length===1)){candidate=hits[0];classification='EAN_IDENTITY';evidence='Globally unique exact-string EAN/barcode';confidence='strong-candidate'}}
        if(!candidate){const exactNames=[...new Set(names.flatMap(n=>freeName.get(nameKey(n))??[]))];const compatible=exactNames.filter(x=>!brandKey||nameKey(x.name).includes(brandKey));if(compatible.length===1){candidate=compatible[0];classification='COMPOUND_STRONG';evidence='Unique normalized name with compatible brand token';confidence='compound-strong'}}
        if(!candidate){let best:{x:XmlRow;score:number}|undefined;const pool=new Set(names.flatMap(n=>tokens(n).flatMap(token=>(freeToken.get(token)??[]).length<=500?freeToken.get(token)??[]:[])));for(const x of pool){const score=Math.max(...names.map(n=>dice(n,x.name)));if(score>=0.72&&(!best||score>best.score))best={x,score}}if(best){candidate=best.x;classification='POSSIBLE_MATCH';evidence=`Name-token similarity ${best.score.toFixed(3)}; evidence only`;confidence='possible'}}
      }
      if(candidate)blockedXml.add(candidate.sku)
      localRows.push({productId:p.id,sku,barcode:ean,name:p.title,brand:p.brand,category:p.category,price:Number(p.price),stock:p.stock,isActive:p.isActive,isDeleted:p.isDeleted,hasSku:Boolean(sku),hasBarcode:Boolean(ean),classification,bestXmlSku:candidate?.sku??'',bestXmlEan:candidate?.ean??'',bestXmlName:candidate?.name??'',xmlPrice2:candidate?.price2??'',xmlAllowedStock:candidate?.allowedStock??'',evidence,confidence,reason:evidence})
    }
    for(const sku of [...AMBIGUOUS,...CASE_REVIEW,...REJECTED.values(),MANUAL_XML_SKU])if(freeSku.has(sku)||freeXml.some(x=>upper(x.sku)===upper(sku)))blockedXml.add(freeXml.find(x=>upper(x.sku)===upper(sku))?.sku??sku)
    const hiddenRows:Record<string,unknown>[]=[],newRows:Record<string,unknown>[]=[]
    for(const x of freeXml){if(blockedXml.has(x.sku))continue;const reasons:string[]=[];const eanHits=x.ean?productEan.get(x.ean)??[]:[];if(eanHits.length)reasons.push(`exact EAN matches Product ${eanHits.map(p=>p.id).join('|')}`);const normalizedEanHits=x.ean?(productNormalizedEan.get(eanKey(x.ean))??[]).filter(p=>s(p.barcode)!==x.ean):[];if(normalizedEanHits.length)reasons.push(`normalized EAN matches Product ${normalizedEanHits.map(p=>p.id).join('|')}`);const exactName=allProductName.get(nameKey(x.name))??[];if(exactName.length)reasons.push(`normalized name matches Product ${exactName.slice(0,10).map(p=>p.id).join('|')}`);const similarSku=new Map<string,Product>();for(const [rule,key] of controlledRelations(x.sku))if(rule!=='CASE_ONLY')for(const p of productNormIndexes.get(rule)?.get(key)??[])if(s(p.sku)!==x.sku)similarSku.set(p.id,p);if(similarSku.size)reasons.push(`controlled-similar SKU Product ${[...similarSku.values()].slice(0,10).map(p=>p.id).join('|')}`);const row={xmlSku:x.sku,xmlEan:x.ean,xmlName:x.name,price2:x.price2,allowedStock:x.allowedStock,price2Positive:x.price2>0,stockPositive:x.allowedStock>0,hasEan:Boolean(x.ean),classification:reasons.length?'POSSIBLE_HIDDEN_DUPLICATE':'NEW_PRODUCT_HIGH_CONFIDENCE',riskReasons:reasons.join('; ')};if(reasons.length)hiddenRows.push(row);else newRows.push(row)}
    const byClass=(rows:Record<string,unknown>[])=>Object.fromEntries([...new Set(rows.map(r=>String(r.classification)))].sort().map(k=>[k,rows.filter(r=>r.classification===k).length]))
    const manualRows=localRows.filter(r=>['MANUAL_REVIEW','REJECTED_MATCH','POSSIBLE_MATCH'].includes(String(r.classification))),strongRows=localRows.filter(r=>['EXACT_IDENTITY','NORMALIZED_IDENTITY','EAN_IDENTITY','COMPOUND_STRONG'].includes(String(r.classification))),activeRows=localRows.filter(r=>r.isActive),localOnly=localRows.filter(r=>r.classification==='LOCAL_ONLY')
    const xmlStats=(rows:Record<string,unknown>[])=>({total:rows.length,price2Positive:rows.filter(r=>Number(r.price2)>0).length,price2Zero:rows.filter(r=>Number(r.price2)===0).length,stockPositive:rows.filter(r=>Number(r.allowedStock)>0).length,stockZero:rows.filter(r=>Number(r.allowedStock)===0).length,price2PositiveAndStockPositive:rows.filter(r=>Number(r.price2)>0&&Number(r.allowedStock)>0).length,withEan:rows.filter(r=>Boolean(r.xmlEan)).length,withoutEan:rows.filter(r=>!r.xmlEan).length})
    const summary={hairshoppro:{linked:linked.length,unlinked:unlinked.length,activeUnlinked:unlinked.filter(p=>p.isActive).length,inactiveUnlinked:unlinked.filter(p=>!p.isActive).length,softDeletedUnlinked:unlinked.filter(p=>p.isDeleted).length,withSku:unlinked.filter(p=>s(p.sku)).length,withoutSku:unlinked.filter(p=>!s(p.sku)).length,withBarcode:unlinked.filter(p=>s(p.barcode)).length,withoutBarcode:unlinked.filter(p=>!s(p.barcode)).length,duplicateSkuValues:[...unlinkedSku.values()].filter(v=>v.length>1).length,duplicateBarcodeValues:[...index(unlinked,p=>s(p.barcode)).values()].filter(v=>v.length>1).length},xml:{records:xml.length,linkedSku:xml.filter(x=>linkedSkus.has(x.sku)).length,freeSku:freeXml.length,withEan:freeXml.filter(x=>x.ean).length,withoutEan:freeXml.filter(x=>!x.ean).length,price2Positive:freeXml.filter(x=>x.price2>0).length,price2Zero:freeXml.filter(x=>x.price2===0).length,stockPositive:freeXml.filter(x=>x.allowedStock>0).length,stockZero:freeXml.filter(x=>x.allowedStock===0).length},matchingFunnel:byClass(localRows),activeUnlinked:{total:activeRows.length,strong:activeRows.filter(r=>strongRows.includes(r)).length,possibleOrManual:activeRows.filter(r=>manualRows.includes(r)).length,localOnly:activeRows.filter(r=>r.classification==='LOCAL_ONLY').length},localOnly:{total:localOnly.length,active:localOnly.filter(r=>r.isActive).length,inactive:localOnly.filter(r=>!r.isActive).length,withSku:localOnly.filter(r=>r.hasSku).length,withoutSku:localOnly.filter(r=>!r.hasSku).length,withBarcode:localOnly.filter(r=>r.hasBarcode).length,withoutBarcode:localOnly.filter(r=>!r.hasBarcode).length},hiddenDuplicates:hiddenRows.length,newProductHighConfidence:xmlStats(newRows),sixthWaveCandidates:strongRows.length}
    if(localRows.length!==unlinked.length||newRows.length+hiddenRows.length+blockedXml.size>freeXml.length)throw new Error('RECONCILIATION_TOTAL_FAILURE')
    const after=await state();if(JSON.stringify(before)!==JSON.stringify(after))throw new Error(`AUDIT_SAFETY_FAILURE:${JSON.stringify({before,after})}`)
    const report={generatedAt:new Date().toISOString(),readOnly:true,databaseWrites:0,xmlSha,xmlRecords:xml.length,before,after,unchanged:true,summary,knownDeferred:{ambiguous:[...AMBIGUOUS],caseReview:[...CASE_REVIEW],manual:{productId:MANUAL_PRODUCT_ID,xmlSku:MANUAL_XML_SKU},rejected:[...REJECTED.entries()]},localProducts:localRows,remainingXml:[...hiddenRows,...newRows]}
    const md=`# Final pre-import reconciliation\n\nGenerated: ${report.generatedAt}\n\nRead-only: **yes** · Database writes: **0** · Fingerprint unchanged: **yes**\n\n## Baseline\n\n- Product: ${before.productCount}; externalId: ${before.externalIdCount}; unlinked: ${before.unlinkedCount}.\n- Active/inactive: ${before.active}/${before.inactive}; SyncRun: ${before.syncRunCount}.\n- Product fingerprint: \`${before.fingerprint}\`.\n- XML: ${xml.length} records; SHA-256: \`${xmlSha}\`.\n\n## Remaining Hairshoppro\n\n- Unlinked: ${summary.hairshoppro.unlinked}; active/inactive: ${summary.hairshoppro.activeUnlinked}/${summary.hairshoppro.inactiveUnlinked}.\n- With/without SKU: ${summary.hairshoppro.withSku}/${summary.hairshoppro.withoutSku}.\n- With/without barcode: ${summary.hairshoppro.withBarcode}/${summary.hairshoppro.withoutBarcode}.\n- LOCAL_ONLY: ${summary.localOnly.total}; active: ${summary.localOnly.active}.\n\n## Remaining XML and matching funnel\n\n- Free XML SKU: ${summary.xml.freeSku}; with/without EAN: ${summary.xml.withEan}/${summary.xml.withoutEan}.\n- Matching classes: \`${JSON.stringify(summary.matchingFunnel)}\`.\n- Possible hidden duplicates: ${summary.hiddenDuplicates}.\n- NEW_PRODUCT_HIGH_CONFIDENCE: ${summary.newProductHighConfidence.total}; price2 > 0: ${summary.newProductHighConfidence.price2Positive}; stock > 0: ${summary.newProductHighConfidence.stockPositive}; both: ${summary.newProductHighConfidence.price2PositiveAndStockPositive}.\n\n## Active unlinked\n\n- Total: ${summary.activeUnlinked.total}; strong: ${summary.activeUnlinked.strong}; possible/manual: ${summary.activeUnlinked.possibleOrManual}; LOCAL_ONLY: ${summary.activeUnlinked.localOnly}.\n- Full review data: \`active-unlinked-final.csv\`.\n\n## Deferred and sixth wave\n\n- Ambiguous SKU, k18/k86, Product 20469, and all nine rejected transformations remain excluded from the new-product scope.\n- Product 20469 remains MANUAL_REVIEW because its local FUDGE brand conflicts with the proposed identity; no correction was made.\n- Potential sixth-wave strong candidates: ${summary.sixthWaveCandidates}; no executable allowlist was created.\n\n## Safety and interpretation\n\n- Classifications are mutually exclusive per local Product.\n- Any XML SKU used by an existing-product candidate, deferred, manual, or rejected collision is excluded from the new-product scope.\n- Price and stock are diagnostic context only, never identity evidence.\n- LOCAL_ONLY does not mean obsolete. No Product was changed or deactivated.\n- No import, sync, commit, or push was performed.\n`
    const remainingLocal=localRows,remainingXml=[...hiddenRows,...newRows]
    await Promise.all([writeFile('second-reconciliation-intermediate.json',JSON.stringify(report,null,2)+'\n'),writeFile('second-reconciliation-intermediate.md',md),writeFile('second-reconciliation-local.csv',csv(remainingLocal)),writeFile('second-reconciliation-xml.csv',csv(remainingXml))])
    console.log(JSON.stringify({before,after,databaseWrites:0,summary,reconciliation:{linkedXml:xml.length-freeXml.length,blockedExistingOrDeferred:freeXml.length-hiddenRows.length-newRows.length,possibleHiddenDuplicates:hiddenRows.length,newProductHighConfidence:newRows.length,total:xml.length},outputs:['second-reconciliation-intermediate.md','second-reconciliation-intermediate.json','second-reconciliation-local.csv','second-reconciliation-xml.csv']},null,2))
  }finally{await prisma.$disconnect()}
}
main().catch(error=>{console.error(error);process.exitCode=1})
