/* eslint-disable @typescript-eslint/no-explicit-any */
import { createHash } from 'node:crypto'
import { readFile,writeFile } from 'node:fs/promises'
import { config } from 'dotenv'
import { XMLParser } from 'fast-xml-parser'
import { GRINS_WAREHOUSE_INDEX_TO_ID } from '../lib/sync/grins-warehouse-map'
import { allowedStock,clean,isStandardEanUpc,median,normalizedEan,normalizedName,numeric,quantile,skuKeys,zeroStockReason } from '../lib/sync/second-new-product-audit'
config({path:'.env.local'})

const XML_SHA='26c001368c79f9cfb9100d1cf67c0a0c479fe181f11e0b15c5944888f6517cad', FIRST_RUN='0e9c0e45-f1bf-4105-8590-b1d64d71cf6a'
const EXPECTED={productCount:8577,externalIdCount:5779,unlinkedCount:2798,active:2229,inactive:6348,syncRunCount:9,fingerprint:'c9eaa51facfe0b6c60ab45bf5589e566'}
type Raw={sku?:string;code?:string;title?:string;price1?:string;price2?:string;price3?:string;price4?:string;warehouses?:{warehouse?:Array<{'@_id':string;'#text'?:string}>}}
type Product={id:string;externalId:string|null;sku:string|null;barcode:string|null;title:string;titleEn:string|null;titleLv:string|null;isActive:boolean;lastSyncRunId:string|null}
const sha=(v:string|Buffer)=>createHash('sha256').update(v).digest('hex')
const index=<T>(rows:T[],key:(row:T)=>string)=>{const out=new Map<string,T[]>();for(const row of rows){const k=key(row);if(k)out.set(k,[...(out.get(k)??[]),row])}return out}
const csv=(rows:Record<string,unknown>[])=>{const cols=[...new Set(rows.flatMap(Object.keys))],q=(v:unknown)=>`"${String(v??'').replace(/"/g,'""')}"`;return '\ufeff'+(cols.length?[cols.map(q).join(','),...rows.map(r=>cols.map(c=>q(r[c])).join(','))].join('\n')+'\n':'')}
const counts=(values:string[])=>Object.fromEntries([...new Set(values)].sort().map(k=>[k,values.filter(v=>v===k).length]))

async function main(){
  const {prisma}=await import('../lib/prisma')
  const state=async()=>(await prisma.$queryRawUnsafe<any[]>(`SELECT COUNT(*)::int "productCount",COUNT("externalId")::int "externalIdCount",COUNT(*) FILTER(WHERE "externalId" IS NULL)::int "unlinkedCount",COUNT(*) FILTER(WHERE "isActive")::int active,COUNT(*) FILTER(WHERE NOT "isActive")::int inactive,(SELECT COUNT(*)::int FROM "SyncRun") "syncRunCount",md5(COALESCE(string_agg(row_to_json(p)::text,'' ORDER BY p.id),'')) fingerprint FROM "Product" p`))[0]
  try{
    const before=await state();for(const [k,v] of Object.entries(EXPECTED))if(before[k]!==v)throw new Error(`SECOND_AUDIT_BASELINE_DRIFT:${JSON.stringify(before)}`)
    const [xmlText,reconText,priorText,firstText]=await Promise.all([readFile('export.xml','utf8'),readFile('second-reconciliation-intermediate.json','utf8'),readFile('final-pre-import-reconciliation.json','utf8'),readFile('first-new-product-import-allowlist.json','utf8')])
    if(sha(xmlText)!==XML_SHA)throw new Error('SECOND_AUDIT_XML_SHA_DRIFT')
    const raw=((new XMLParser({ignoreAttributes:false,attributeNamePrefix:'@_',parseTagValue:false,processEntities:false,isArray:n=>n==='item'||n==='warehouse'}).parse(xmlText) as {root?:{item?:Raw[]}}).root?.item??[])
    const uniqueSku=new Set(raw.map(x=>clean(x.sku)));if(raw.length!==16176||uniqueSku.size!==16176||uniqueSku.has(''))throw new Error('SECOND_AUDIT_XML_CARDINALITY_DRIFT')
    const recon=JSON.parse(reconText),prior=JSON.parse(priorText),first=JSON.parse(firstText),products=await prisma.product.findMany({select:{id:true,externalId:true,sku:true,barcode:true,title:true,titleEn:true,titleLv:true,isActive:true,lastSyncRunId:true}}) as Product[]
    const firstSkus=new Set<string>(first.entries.map((x:any)=>x.xmlSku)),firstProducts=products.filter(p=>p.externalId&&firstSkus.has(p.externalId)),lastRun=await prisma.syncRun.findFirst({orderBy:{startedAt:'desc'}})
    if(firstProducts.length!==2199||firstProducts.some(p=>p.isActive)||lastRun?.id!==FIRST_RUN)throw new Error('SECOND_AUDIT_FIRST_WAVE_INTEGRITY_FAILURE')
    const newRows=recon.remainingXml.filter((r:any)=>r.classification==='NEW_PRODUCT_HIGH_CONFIDENCE'),newSkus=new Set<string>(newRows.map((r:any)=>r.xmlSku)),rawNew=raw.filter(x=>newSkus.has(clean(x.sku)))
    const parse=(x:Raw)=>{const warehouses:Record<string,number>={};for(const w of x.warehouses?.warehouse??[]){const id=GRINS_WAREHOUSE_INDEX_TO_ID[Number(w['@_id'])-1];if(id)warehouses[id]=numeric(w['#text'])}return{sku:clean(x.sku),ean:clean(x.code),name:clean(x.title),price1:numeric(x.price1),price2:numeric(x.price2),price2Raw:clean(x.price2),price3:numeric(x.price3),price4:numeric(x.price4),warehouses,stock:allowedStock(warehouses)}}
    const parsedNew=rawNew.map(parse),matrix={A:parsedNew.filter(x=>x.price2>0&&x.stock>0).length,B:parsedNew.filter(x=>x.price2>0&&x.stock===0).length,C:parsedNew.filter(x=>x.price2===0&&x.stock>0).length,D:parsedNew.filter(x=>x.price2===0&&x.stock===0).length}
    if(Object.values(matrix).reduce((a,b)=>a+b,0)!==newRows.length)throw new Error('SECOND_AUDIT_MATRIX_FAILURE')
    const groupB=parsedNew.filter(x=>x.price2>0&&x.stock===0),prices=groupB.map(x=>x.price2),q1=quantile(prices,.25),q3=quantile(prices,.75),iqr=q3-q1,outlierLow=Math.max(0,q1-3*iqr),outlierHigh=q3+3*iqr
    const productExt=index(products,p=>clean(p.externalId)),productSku=index(products,p=>clean(p.sku)),productEan=index(products,p=>normalizedEan(p.barcode)),productName=new Map<string,Product[]>(),productSkuKeys=new Map<string,Product[]>()
    for(const p of products){for(const name of [p.title,p.titleEn,p.titleLv]){const k=normalizedName(name);if(k)productName.set(k,[...(productName.get(k)??[]),p])}for(const k of skuKeys(p.sku))productSkuKeys.set(k,[...(productSkuKeys.get(k)??[]),p])}
    const xmlEan=index(raw.map(parse),x=>normalizedEan(x.ean)),auditRows=groupB.map(x=>{
      const reasons:string[]=[],hard:string[]=[],hidden:string[]=[],review:string[]=[]
      if(productExt.has(x.sku))hard.push('existing externalId claimant')
      if(productSku.has(x.sku))hard.push('exact local SKU claimant')
      const eanKey=normalizedEan(x.ean),eanLocal=eanKey?(productEan.get(eanKey)??[]):[];if(eanLocal.length)hard.push(`local barcode claimant:${eanLocal.map(p=>p.id).join('|')}`)
      if(eanKey&&(xmlEan.get(eanKey)?.length??0)>1)hard.push(`duplicate XML EAN:${xmlEan.get(eanKey)!.length}`)
      const normalizedClaimants=new Map<string,Product>();for(const k of skuKeys(x.sku))for(const p of productSkuKeys.get(k)??[])if(clean(p.sku)!==x.sku)normalizedClaimants.set(p.id,p)
      if(normalizedClaimants.size)hidden.push(`case/normalized SKU claimant:${[...normalizedClaimants.keys()].join('|')}`)
      const nameClaimants=productName.get(normalizedName(x.name))??[];if(nameClaimants.length)hidden.push(`normalized name claimant:${nameClaimants.map(p=>p.id).join('|')}`)
      if(!Number.isFinite(x.price2)||x.price2<=0)hard.push('invalid price2')
      if(x.stock!==0)hard.push('allowed stock is not zero')
      if(!/^\d+(?:\.\d{1,2})?$/u.test(x.price2Raw))review.push(`non-standard price2 format:${x.price2Raw}`)
      if(x.price2<outlierLow||x.price2>outlierHigh)review.push(`price outlier outside ${outlierLow.toFixed(2)}..${outlierHigh.toFixed(2)}`)
      const classification=hard.length?'REJECTED':hidden.length?'POSSIBLE_HIDDEN_DUPLICATE':review.length?'MANUAL_REVIEW':'SECOND_IMPORT_SAFE_CANDIDATE';reasons.push(...hard,...hidden,...review)
      return{classification,xmlSku:x.sku,ean:x.ean,xmlName:x.name,price1:x.price1,price2:x.price2,price2Raw:x.price2Raw,price3:x.price3,price4:x.price4,allowedStock:x.stock,warehouseSnapshot:JSON.stringify(x.warehouses),zeroStockReason:zeroStockReason(x.warehouses),eanPresent:Boolean(x.ean),eanStandardValid:isStandardEanUpc(x.ean),eanInternalOrNonStandard:Boolean(x.ean)&&!isStandardEanUpc(x.ean),xmlEanOccurrences:eanKey?(xmlEan.get(eanKey)?.length??0):0,localBarcodeClaimants:eanLocal.length,riskReasons:reasons.join('; '),externalId:x.sku,sku:x.sku,barcode:x.ean||null,price:x.price2,stock:0,isActive:false,brand:'',category:'uncategorized'}
    })
    const safe=auditRows.filter(x=>x.classification==='SECOND_IMPORT_SAFE_CANDIDATE'),hidden=auditRows.filter(x=>x.classification==='POSSIBLE_HIDDEN_DUPLICATE'),review=auditRows.filter(x=>x.classification==='MANUAL_REVIEW'),rejected=auditRows.filter(x=>x.classification==='REJECTED')
    const priorNew=new Set<string>(prior.remainingXml.filter((r:any)=>r.classification==='NEW_PRODUCT_HIGH_CONFIDENCE').map((r:any)=>r.xmlSku)),currentOrImported=new Set([...newSkus,...firstSkus]),disappeared=[...priorNew].filter(s=>!currentOrImported.has(s)),newlyAppeared=[...newSkus].filter(s=>!priorNew.has(s)),classificationDrift=[...priorNew].filter(s=>!newSkus.has(s)&&!firstSkus.has(s))
    const manual=19,linked=5779,hiddenTotal=Number(recon.summary.hiddenDuplicates),fresh=Number(recon.summary.newProductHighConfidence.total),existing=16176-linked-manual-hiddenTotal-fresh,reconciliation={ALREADY_LINKED:linked,EXISTING_PRODUCT_CANDIDATE:existing,MANUAL_OR_DEFERRED:manual,POSSIBLE_HIDDEN_DUPLICATE:hiddenTotal,NEW_PRODUCT_HIGH_CONFIDENCE:fresh}
    const eanAnalysis={present:safe.filter(x=>x.eanPresent).length,missing:safe.filter(x=>!x.eanPresent).length,validStandard:safe.filter(x=>x.eanStandardValid).length,internalOrNonStandard:safe.filter(x=>x.eanInternalOrNonStandard).length,duplicateXml:safe.filter(x=>x.xmlEanOccurrences>1).length,localClaimant:safe.filter(x=>x.localBarcodeClaimants>0).length,globallyUnique:safe.filter(x=>x.eanPresent&&x.xmlEanOccurrences===1&&!x.localBarcodeClaimants).length}
    const sortedPrices=[...groupB].sort((a,b)=>a.price2-b.price2),priceAnalysis={min:Math.min(...prices),max:Math.max(...prices),median:median(prices),q1,q3,outlierLow,outlierHigh,outliers:auditRows.filter(x=>x.riskReasons.includes('price outlier')).length,invalidFormat:auditRows.filter(x=>x.riskReasons.includes('non-standard price2 format')).length,finitePositive:groupB.filter(x=>Number.isFinite(x.price2)&&x.price2>0).length,lowest:sortedPrices.slice(0,10).map(x=>({sku:x.sku,price2:x.price2,raw:x.price2Raw})),highest:sortedPrices.slice(-10).reverse().map(x=>({sku:x.sku,price2:x.price2,raw:x.price2Raw}))}
    const zeroStockAnalysis={allGroupB:counts(auditRows.map(x=>x.zeroStockReason)),safeOnly:counts(safe.map(x=>x.zeroStockReason))},oldHidden=new Set<string>(prior.remainingXml.filter((r:any)=>r.classification==='POSSIBLE_HIDDEN_DUPLICATE').map((r:any)=>r.xmlSku)),currentHidden=new Set<string>(recon.remainingXml.filter((r:any)=>r.classification==='POSSIBLE_HIDDEN_DUPLICATE').map((r:any)=>r.xmlSku)),newHiddenAfterFirst=[...currentHidden].filter(s=>!oldHidden.has(s))
    const after=await state();if(JSON.stringify(before)!==JSON.stringify(after))throw new Error('SECOND_AUDIT_DATABASE_CHANGED')
    const report={generatedAt:new Date().toISOString(),readOnly:true,executable:false,authorizedForApply:false,databaseWrites:0,before,after,xml:{records:raw.length,uniqueSku:uniqueSku.size,sha256:sha(xmlText)},firstWave:{found:firstProducts.length,active:firstProducts.filter(p=>p.isActive).length,inactive:firstProducts.filter(p=>!p.isActive).length,lastRun},reconciliation,remaining:{theoretical:9989,reconstructed:fresh,disappeared:disappeared.length,newlyAppeared:newlyAppeared.length,classificationDrift:classificationDrift.length,newHiddenAfterFirst:newHiddenAfterFirst.length,newHiddenAfterFirstSkus:newHiddenAfterFirst},matrix,secondImportGroupB:groupB.length,identityAudit:{safe:safe.length,hiddenDuplicate:hidden.length,manualReview:review.length,rejected:rejected.length},eanAnalysis,priceAnalysis,zeroStockAnalysis,adminReadiness:{distinguishImported:'Database lastSyncRunId can identify the first-wave rows, but the Admin Products API/UI does not expose or filter it.',completenessFilters:'No dedicated missing brand/category/image/content filters.',bulkFind:'Only indirect hidden/search/category filtering; no ERP-import batch filter.',sufficient:false,minimalWorkflow:'Add read-only import-batch/lastSyncRunId and completeness filters, a pending ERP queue, persisted selection across pagination, and guarded bulk enrichment/activation.'},safeCandidates:safe}
    const md=`# Second new-product import audit\n\nRead-only: **yes** · Executable: **no** · Authorized for apply: **no** · Database writes: **0**\n\n## Baseline\n\n- Product/externalId/unlinked: ${before.productCount}/${before.externalIdCount}/${before.unlinkedCount}.\n- Active/inactive/SyncRun: ${before.active}/${before.inactive}/${before.syncRunCount}.\n- Fingerprint: \`${before.fingerprint}\`.\n- XML records/unique SKU: ${raw.length}/${uniqueSku.size}; SHA-256: \`${sha(xmlText)}\`.\n\n## Reconstructed reconciliation\n\n${Object.entries(reconciliation).map(([k,v])=>`- ${k}: ${v}`).join('\n')}\n\nTotal: **${Object.values(reconciliation).reduce((a,b)=>a+b,0)}**.\n\n## Remaining high-confidence\n\n- Theoretical/reconstructed: 9989/${fresh}.\n- Disappeared/newly appeared/classification drift: ${disappeared.length}/${newlyAppeared.length}/${classificationDrift.length}.\n- New hidden signals after first wave: ${newHiddenAfterFirst.length}.\n\n## Price × stock matrix\n\n- A: ${matrix.A}; B: ${matrix.B}; C: ${matrix.C}; D: ${matrix.D}.\n\n## Group B identity audit\n\n- SAFE: ${safe.length}; hidden duplicate: ${hidden.length}; manual review: ${review.length}; rejected: ${rejected.length}.\n\n## EAN\n\n${JSON.stringify(eanAnalysis)}\n\n## Price\n\n${JSON.stringify(priceAnalysis)}\n\n## Zero stock\n\n${JSON.stringify(zeroStockAnalysis)}\n\n## Admin readiness\n\nCurrent UI is not sufficient for safe preparation of thousands of pending ERP cards. It supports hidden/search/category views, but not import-batch or completeness filters. Minimal later workflow: import-batch queue, missing-field filters, persisted bulk selection and guarded activation.\n`
    const matrixRows=parsedNew.map(x=>({xmlSku:x.sku,ean:x.ean,price2:x.price2,allowedStock:x.stock,group:x.price2>0?(x.stock>0?'A':'B'):(x.stock>0?'C':'D'),warehouseSnapshot:JSON.stringify(x.warehouses)}))
    await Promise.all([writeFile('second-new-product-import-audit.json',JSON.stringify(report,null,2)+'\n'),writeFile('second-new-product-import-audit.md',md),writeFile('second-new-product-import-safe-candidates.csv',csv(safe)),writeFile('second-new-product-import-review.csv',csv(review)),writeFile('second-new-product-import-hidden-duplicates.csv',csv(hidden)),writeFile('second-new-product-import-rejected.csv',csv(rejected)),writeFile('remaining-new-products-by-price-stock.csv',csv(matrixRows)),writeFile('second-new-product-import-safe-candidates.json',JSON.stringify({schemaVersion:1,wave:'second-new-product-import-diagnostic',executable:false,authorizedForApply:false,xmlSha256:XML_SHA,baseline:before,entryCount:safe.length,entries:safe},null,2)+'\n')])
    console.log(JSON.stringify({...report,safeCandidates:undefined},null,2))
  }finally{await prisma.$disconnect()}
}
main().catch(e=>{console.error(e);process.exitCode=1})
