/* eslint-disable @typescript-eslint/no-explicit-any */
import { createHash } from 'node:crypto'
import { readFile, writeFile } from 'node:fs/promises'
import { config } from 'dotenv'
import { XMLParser } from 'fast-xml-parser'
import { GRINS_WAREHOUSE_INDEX_TO_ID } from '../lib/sync/grins-warehouse-map'
import { allowedStock, classifyPriceReview, clean, csv, excludedStock, normalizedName, normalizedSku, numeric, priceStockCell } from '../lib/sync/final-remaining-audit'

config({ path: '.env.local' })

const XML_SHA = '26c001368c79f9cfb9100d1cf67c0a0c479fe181f11e0b15c5944888f6517cad'
const EXPECTED = { productCount:18544, externalIdCount:15754, unlinkedCount:2790, active:2229, inactive:16315, syncRunCount:12 }
type Warehouse = {'@_id':string;'#text'?:string}
type Raw = {sku?:string;code?:string;title?:string;price1?:string;price2?:string;price3?:string;price4?:string;warehouses?:{warehouse?:Warehouse[]}}
type XmlRow = {sku:string;ean:string;name:string;price1:number;price2:number;price2Raw:string;price3:number;price4:number;warehouses:Record<string,number>;allowedStock:number;excludedStock:number}
type Product = {id:string;externalId:string|null;sku:string|null;barcode:string|null;title:string;titleEn:string|null;titleLv:string|null;brand:string;category:string;specVolume:string|null;specType:string|null;price:unknown;stock:number;isActive:boolean;isDeleted:boolean;lastSyncRunId:string|null}
type Category = 'EXISTING_PRODUCT_CANDIDATE'|'MANUAL_OR_DEFERRED'|'POSSIBLE_HIDDEN_DUPLICATE'|'NEW_PRODUCT_CANDIDATE'

const sha=(value:string|Buffer)=>createHash('sha256').update(value).digest('hex')
const index=<T>(rows:T[],key:(row:T)=>string)=>{const result=new Map<string,T[]>();for(const row of rows){const value=key(row);if(value)result.set(value,[...(result.get(value)??[]),row])}return result}
const state=async(prisma:any)=>(await prisma.$queryRawUnsafe(`SELECT COUNT(*)::int "productCount",COUNT("externalId")::int "externalIdCount",COUNT(*) FILTER(WHERE "externalId" IS NULL)::int "unlinkedCount",COUNT(*) FILTER(WHERE "isActive")::int active,COUNT(*) FILTER(WHERE NOT "isActive")::int inactive,(SELECT COUNT(*)::int FROM "SyncRun") "syncRunCount",(SELECT COUNT(*)::int FROM (SELECT "externalId" FROM "Product" WHERE "externalId" IS NOT NULL GROUP BY "externalId" HAVING COUNT(*)>1)d) "duplicateExternalId",md5(COALESCE(string_agg(row_to_json(p)::text,'' ORDER BY p.id),'')) fingerprint FROM "Product" p`))[0] as Record<string,unknown>
const rowBase=(x:XmlRow)=>({xmlSku:x.sku,ean:x.ean,name:x.name,price1:x.price1,price2:x.price2,price2Raw:x.price2Raw,price3:x.price3,price4:x.price4,allowedStock:x.allowedStock,excludedStock:x.excludedStock,stockOnlyExcluded:x.allowedStock===0&&x.excludedStock>0,warehouseDistribution:JSON.stringify(x.warehouses)})

async function main(){
  const {prisma}=await import('../lib/prisma')
  try{
    const before=await state(prisma),xmlText=await readFile('export.xml','utf8'),xmlHash=sha(xmlText)
    const raw=((new XMLParser({ignoreAttributes:false,attributeNamePrefix:'@_',parseTagValue:false,processEntities:false,isArray:name=>name==='item'||name==='warehouse'}).parse(xmlText) as {root?:{item?:Raw[]}}).root?.item??[])
    const xml:XmlRow[]=raw.map(item=>{const warehouses:Record<string,number>={};for(const warehouse of item.warehouses?.warehouse??[]){const id=GRINS_WAREHOUSE_INDEX_TO_ID[Number(warehouse['@_id'])-1];if(id)warehouses[id]=numeric(warehouse['#text'])}return{sku:clean(item.sku),ean:clean(item.code),name:clean(item.title),price1:numeric(item.price1),price2:numeric(item.price2),price2Raw:clean(item.price2),price3:numeric(item.price3),price4:numeric(item.price4),warehouses,allowedStock:allowedStock(warehouses),excludedStock:excludedStock(warehouses)}})
    const uniqueSku=new Set(xml.map(row=>row.sku)).size
    if(xmlHash!==XML_SHA||xml.length!==16176||uniqueSku!==16176)throw new Error(`XML_GATE_FAILED:${JSON.stringify({xmlHash,records:xml.length,uniqueSku})}`)
    for(const [key,value] of Object.entries(EXPECTED))if(before[key]!==value)throw new Error(`BASELINE_GATE_FAILED:${JSON.stringify(before)}`)
    if(before.duplicateExternalId!==0)throw new Error(`DUPLICATE_EXTERNAL_ID:${before.duplicateExternalId}`)

    const products=await prisma.product.findMany({select:{id:true,externalId:true,sku:true,barcode:true,title:true,titleEn:true,titleLv:true,brand:true,category:true,specVolume:true,specType:true,price:true,stock:true,isActive:true,isDeleted:true,lastSyncRunId:true}}) as Product[]
    const linkedExternal=new Set(products.filter(p=>p.externalId).map(p=>p.externalId!)),linkedRows=xml.filter(row=>linkedExternal.has(row.sku)),remaining=xml.filter(row=>!linkedExternal.has(row.sku))
    const unlinked=products.filter(p=>!p.externalId),bySku=index(unlinked,p=>clean(p.sku)),byEan=index(unlinked,p=>clean(p.barcode)),allSku=index(products,p=>clean(p.sku)),allEan=index(products,p=>clean(p.barcode)),byNormSku=index(unlinked,p=>normalizedSku(p.sku)),allNormName=new Map<string,Product[]>()
    for(const product of products)for(const title of [product.title,product.titleEn,product.titleLv]){const key=normalizedName(title);if(key)allNormName.set(key,[...(allNormName.get(key)??[]),product])}

    const classified:Record<string,unknown>[]=[],claimedProducts=new Set<string>()
    for(const item of remaining){
      const exactSku=bySku.get(item.sku)??[],exactEan=item.ean?byEan.get(item.ean)??[]:[],normSku=byNormSku.get(normalizedSku(item.sku))?.filter(p=>clean(p.sku)!==item.sku)??[]
      const globalExactSku=allSku.get(item.sku)??[],globalExactEan=item.ean?allEan.get(item.ean)??[]:[]
      let category:Category='NEW_PRODUCT_CANDIDATE',detail='NO_EXISTING_IDENTITY_EVIDENCE',match:Product|undefined,evidence='No Product claims externalId, exact SKU or barcode; no hidden-duplicate evidence'
      if(exactSku.length===1&&globalExactSku.length===1){category='EXISTING_PRODUCT_CANDIDATE';detail='SAFE_FUTURE_BACKFILL';match=exactSku[0];evidence='Globally unique exact SKU on unlinked Product'}
      else if(exactEan.length===1&&globalExactEan.length===1){category='EXISTING_PRODUCT_CANDIDATE';detail='SAFE_FUTURE_BACKFILL';match=exactEan[0];evidence='Globally unique exact EAN on unlinked Product'}
      else if(exactSku.length||exactEan.length){category='EXISTING_PRODUCT_CANDIDATE';detail='MANUAL_REVIEW';match=(exactSku[0]??exactEan[0]);evidence='Exact identity evidence is non-unique or contradictory'}
      else if(normSku.length===1){category='EXISTING_PRODUCT_CANDIDATE';detail='MANUAL_REVIEW';match=normSku[0];evidence='Unique controlled normalized-SKU evidence; not exact'}
      else if(normSku.length>1){category='MANUAL_OR_DEFERRED';detail='INSUFFICIENT_EVIDENCE';evidence='Normalized SKU has multiple local claimants'}
      else {
        const nameHits=allNormName.get(normalizedName(item.name))??[],barcodeHits=item.ean?allEan.get(item.ean)??[]:[]
        if(barcodeHits.length===1){category='POSSIBLE_HIDDEN_DUPLICATE';detail='CONFIRMED_EXISTING_PRODUCT';match=barcodeHits[0];evidence='Exact barcode already claimed by Product'}
        else if(barcodeHits.length>1){category='POSSIBLE_HIDDEN_DUPLICATE';detail='AMBIGUOUS';evidence='Duplicate EAN has multiple Product claimants'}
        else if(nameHits.length===1){category='POSSIBLE_HIDDEN_DUPLICATE';detail='STRONG_EXISTING_PRODUCT_CANDIDATE';match=nameHits[0];evidence='Unique normalized full-name match'}
        else if(nameHits.length>1){category='POSSIBLE_HIDDEN_DUPLICATE';detail='AMBIGUOUS';evidence='Normalized full name has multiple Product claimants'}
      }
      if(match){if(claimedProducts.has(match.id)){category='MANUAL_OR_DEFERRED';detail='INSUFFICIENT_EVIDENCE';evidence+='; Product is also claimed by another XML SKU'}claimedProducts.add(match.id)}
      classified.push({...rowBase(item),category,detail,evidence,productId:match?.id??'',productSku:match?.sku??'',productBarcode:match?.barcode??'',productTitle:match?.title??'',productActive:match?.isActive??'',productDeleted:match?.isDeleted??'',productBrand:match?.brand??'',productVolume:match?.specVolume??'',productType:match?.specType??''})
    }

    const previousAllowlist=JSON.parse(await readFile('second-new-product-import-allowlist.json','utf8')) as {reviewExcludedSkus:string[];entries:Array<{xmlSku:string}>}
    const previousRecon=JSON.parse(await readFile('second-reconciliation-intermediate.json','utf8')) as {remainingXml:Array<{xmlSku:string;classification:string}>;knownDeferred:{ambiguous:string[];caseReview:string[];manual:{xmlSku:string};rejected:Array<[string,string]>}}
    const priorReview=new Set(previousAllowlist.reviewExcludedSkus),positivePrices=remaining.map(x=>x.price2).filter(x=>x>0).sort((a,b)=>a-b),quantile=(q:number)=>{const pos=(positivePrices.length-1)*q,base=Math.floor(pos),rest=pos-base;return positivePrices[base]+((positivePrices[base+1]??positivePrices[base])-positivePrices[base])*rest},q1=quantile(.25),q3=quantile(.75),iqr=q3-q1,outlierLow=Math.max(0,q1-1.5*iqr),outlierHigh=q3+1.5*iqr
    const priceReview=classified.filter(row=>priorReview.has(String(row.xmlSku))).map(row=>{const assessment=classifyPriceReview({price2Raw:String(row.price2Raw),price1:Number(row.price1),price2:Number(row.price2),price3:Number(row.price3),price4:Number(row.price4),outlierLow,outlierHigh});return{...row,priceReviewClassification:assessment.classification,priceReviewReason:assessment.reason,technicallyExactImportable:assessment.technicallyExactImportable,currentCategory:row.category}})
    const newRows=classified.filter(row=>row.category==='NEW_PRODUCT_CANDIDATE'),matrix=Object.fromEntries(['A','B','C','D'].map(cell=>[cell,newRows.filter(row=>priceStockCell(Number(row.price2),Number(row.allowedStock))===cell).length])),stockOnlyExcluded=newRows.filter(row=>row.stockOnlyExcluded).length
    const existing=classified.filter(row=>row.category==='EXISTING_PRODUCT_CANDIDATE'),hidden=classified.filter(row=>row.category==='POSSIBLE_HIDDEN_DUPLICATE'),manual=classified.filter(row=>row.category==='MANUAL_OR_DEFERRED')
    const localRows=unlinked.map(product=>{const candidates=classified.filter(row=>row.productId===product.id);return{productId:product.id,sku:product.sku??'',barcode:product.barcode??'',title:product.title,isActive:product.isActive,isDeleted:product.isDeleted,hasSku:Boolean(clean(product.sku)),hasBarcode:Boolean(clean(product.barcode)),xmlCandidateCount:candidates.length,xmlCandidates:candidates.map(row=>row.xmlSku).join('|'),classification:candidates.length?'HAS_XML_CANDIDATE':'LOCAL_ONLY',lastSyncRunId:product.lastSyncRunId??''}})
    const categories={ALREADY_LINKED:linkedRows.length,EXISTING_PRODUCT_CANDIDATE:existing.length,MANUAL_OR_DEFERRED:manual.length,POSSIBLE_HIDDEN_DUPLICATE:hidden.length,NEW_PRODUCT_CANDIDATE:newRows.length}
    if(Object.values(categories).reduce((a,b)=>a+b,0)!==xml.length||classified.length!==remaining.length)throw new Error('RECONCILIATION_TOTAL_FAILED')
    const importedRuns=await prisma.syncRun.findMany({where:{triggeredBy:{contains:'new-product-import'}},select:{id:true,triggeredBy:true,productsTotal:true,productsSynced:true,status:true},orderBy:{startedAt:'asc'}})
    const after=await state(prisma);if(JSON.stringify(before)!==JSON.stringify(after))throw new Error(`DATABASE_CHANGED:${JSON.stringify({before,after})}`)
    const counts=(rows:Record<string,unknown>[],key:string)=>Object.fromEntries([...new Set(rows.map(r=>String(r[key])))].sort().map(value=>[value,rows.filter(r=>String(r[key])===value).length]))
    const previousHidden=new Set(previousRecon.remainingXml.filter(row=>row.classification==='POSSIBLE_HIDDEN_DUPLICATE').map(row=>row.xmlSku))
    const previousManual=new Set([...previousRecon.knownDeferred.ambiguous,...previousRecon.knownDeferred.caseReview,previousRecon.knownDeferred.manual.xmlSku,...previousRecon.knownDeferred.rejected.map(([,xmlSku])=>xmlSku)].filter(sku=>!linkedExternal.has(sku)))
    const previousNew=new Set(previousRecon.remainingXml.filter(row=>row.classification==='NEW_PRODUCT_HIGH_CONFIDENCE').map(row=>row.xmlSku))
    const previousExisting=new Set(remaining.map(row=>row.sku).filter(sku=>!previousHidden.has(sku)&&!previousManual.has(sku)&&!previousNew.has(sku)))
    const fate=(scope:Set<string>,expectedCategory:string)=>{const rows=classified.filter(row=>scope.has(String(row.xmlSku))),linked=[...scope].filter(sku=>linkedExternal.has(sku));return{previous:scope.size,remaining:rows.length,linked:linked.length,classificationNow:counts(rows,'category'),changedClassification:rows.filter(row=>row.category!==expectedCategory).length,changedSkus:rows.filter(row=>row.category!==expectedCategory).map(row=>row.xmlSku)}}
    const priorFate={review:{...fate(priorReview,'NEW_PRODUCT_CANDIDATE'),priceReviewClasses:counts(priceReview,'priceReviewClassification'),technicallyExactImportable:priceReview.filter(row=>row.technicallyExactImportable).length},hidden:fate(previousHidden,'POSSIBLE_HIDDEN_DUPLICATE'),manual:fate(previousManual,'MANUAL_OR_DEFERRED'),existing:fate(previousExisting,'EXISTING_PRODUCT_CANDIDATE')}
    const localSummary={total:unlinked.length,active:unlinked.filter(p=>p.isActive).length,inactive:unlinked.filter(p=>!p.isActive).length,withSku:unlinked.filter(p=>clean(p.sku)).length,withoutSku:unlinked.filter(p=>!clean(p.sku)).length,withBarcode:unlinked.filter(p=>clean(p.barcode)).length,withoutBarcode:unlinked.filter(p=>!clean(p.barcode)).length,withXmlCandidate:localRows.filter(r=>r.classification==='HAS_XML_CANDIDATE').length,localOnly:localRows.filter(r=>r.classification==='LOCAL_ONLY').length}
    const safeExisting=existing.filter(row=>row.detail==='SAFE_FUTURE_BACKFILL').length,safeNew=newRows.filter(row=>previousNew.has(String(row.xmlSku))&&(!priorReview.has(String(row.xmlSku))||priceReview.find(p=>String((p as Record<string,unknown>).xmlSku)===String(row.xmlSku))?.technicallyExactImportable)).length
    const adminReadiness={importRuns:importedRuns,distinguishableInDatabase:true,lastSyncRunIdInProductModel:true,adminApiFilterAvailable:false,minimumChange:'Expose lastSyncRunId/import batch in admin Product DTO and add an exact batch filter plus bulk-review status; keep activation explicit.'}
    const report={generatedAt:new Date().toISOString(),readOnly:true,databaseWrites:0,xml:{records:xml.length,uniqueSku,sha256:xmlHash},before,after,unchanged:true,categories,remaining:remaining.length,matrix,stockOnlyExcluded,priceReview:{outlierLow,outlierHigh,summary:counts(priceReview,'priceReviewClassification'),technicallyExactImportable:priceReview.filter(r=>r.technicallyExactImportable).length,rows:priceReview},hiddenDuplicates:{summary:counts(hidden,'detail'),rows:hidden},existingCandidates:{summary:counts(existing,'detail'),rows:existing},manualDeferred:{summary:counts(manual,'detail'),rows:manual},newProductCandidates:{safeAutomatic:safeNew,conservativeRule:'Must belong to the prior high-confidence new-product scope and pass all fresh identity/field gates; previously deferred identity scopes are not auto-cleared.',rows:newRows},priorFate,localProducts:{summary:localSummary,rows:localRows},adminReadiness,safeExisting,safeNew,manualReviewRemaining:remaining.length-safeExisting-safeNew}
    const table=Object.entries(categories).map(([key,value])=>`| ${key} | ${value} |`).join('\n')
    const md=`# Final remaining XML audit\n\nGenerated: ${report.generatedAt}\n\nRead-only: **yes** · database writes: **0** · fingerprint unchanged: **yes**\n\n## Baseline\n\n- Product/externalId: ${before.productCount}/${before.externalIdCount}; active/inactive: ${before.active}/${before.inactive}; SyncRun: ${before.syncRunCount}; duplicate externalId: ${before.duplicateExternalId}.\n- Fingerprint: \`${before.fingerprint}\`.\n- XML records/unique SKU: ${xml.length}/${uniqueSku}; SHA-256: \`${xmlHash}\`.\n\n## Full XML reconciliation\n\n| Category | Count |\n|---|---:|\n${table}\n| **TOTAL** | **${Object.values(categories).reduce((a,b)=>a+b,0)}** |\n\n## Remaining XML\n\nExact remaining scope: **${remaining.length}**.\n\n## Price × stock matrix (new-product candidates)\n\n- A price2 > 0, stock > 0: ${matrix.A}\n- B price2 > 0, stock = 0: ${matrix.B}\n- C price2 = 0, stock > 0: ${matrix.C}\n- D price2 = 0, stock = 0: ${matrix.D}\n- Stock only on excluded warehouses: ${stockOnlyExcluded}\n\n## Price review\n\nPrevious 429 currently found: ${priceReview.length}; classes: \`${JSON.stringify(report.priceReview.summary)}\`; technically exact-importable without correction: ${report.priceReview.technicallyExactImportable}.\n\n## Hidden duplicates\n\n${hidden.length}; classes: \`${JSON.stringify(report.hiddenDuplicates.summary)}\`.\n\n## Existing Product candidates\n\n${existing.length}; classes: \`${JSON.stringify(report.existingCandidates.summary)}\`; SAFE_FUTURE_BACKFILL: ${safeExisting}. No allowlist created.\n\n## Automatic new-product candidates\n\nTotal: ${newRows.length}; technically safe under current identity/field gates: ${safeNew}. No executable allowlist created.\n\n## Local-only Product\n\n\`${JSON.stringify(localSummary)}\`. LOCAL_ONLY is not an obsolescence decision.\n\n## Admin readiness\n\nDatabase batches are distinguishable by lastSyncRunId, but current Admin/API has no batch filter. Minimum: ${adminReadiness.minimumChange}\n\n## Safety\n\nBefore and after state is byte-for-byte equal at the aggregate/fingerprint level. No import, sync, activation, deactivation, backup, commit, or push.\n`
    await Promise.all([
      writeFile('final-remaining-xml-audit.json',JSON.stringify(report,null,2)+'\n'),writeFile('final-remaining-xml-audit.md',md),writeFile('remaining-new-product-candidates.csv',csv(newRows)),writeFile('remaining-existing-product-candidates.csv',csv(existing)),writeFile('remaining-hidden-duplicates.csv',csv(hidden)),writeFile('remaining-price-review.csv',csv(priceReview)),writeFile('remaining-manual-deferred.csv',csv(manual)),writeFile('remaining-local-only.csv',csv(localRows)),
    ])
    console.log(JSON.stringify({before,after,databaseWrites:0,categories,remaining:remaining.length,matrix,stockOnlyExcluded,priceReview:{summary:report.priceReview.summary,technicallyExactImportable:report.priceReview.technicallyExactImportable},hiddenDuplicates:report.hiddenDuplicates.summary,existingCandidates:report.existingCandidates.summary,priorFate,safeExisting,safeNew,manualReviewRemaining:report.manualReviewRemaining,localSummary,adminReadiness,artifacts:['final-remaining-xml-audit.md','final-remaining-xml-audit.json','remaining-new-product-candidates.csv','remaining-existing-product-candidates.csv','remaining-hidden-duplicates.csv','remaining-price-review.csv','remaining-manual-deferred.csv','remaining-local-only.csv']},null,2))
  }finally{await prisma.$disconnect()}
}
main().catch(error=>{console.error(error);process.exitCode=1})
