import { config } from 'dotenv';config({path:'.env.local'})
import { readFile } from 'node:fs/promises'
import { assertBaseline,FINAL_EXISTING_ALLOWLIST_SHA,parseAllowlist,validateScope,type ProductIdentity,type State } from '../lib/sync/final-existing-backfill'
const arg=(name:string)=>{const i=process.argv.indexOf(name);return i<0?undefined:process.argv[i+1]}
const select={id:true,externalId:true,sku:true,barcode:true,title:true,titleEn:true,titleLv:true,brand:true,category:true,description:true,image:true,images:true,price:true,stock:true,isActive:true,isDeleted:true,createdAt:true,updatedAt:true,lastSyncRunId:true} as const
const state=async(db:any)=>(await db.$queryRawUnsafe(`SELECT COUNT(*)::int "productCount",COUNT("externalId")::int "externalIdCount",COUNT(*) FILTER(WHERE "externalId" IS NULL)::int "unlinkedCount",COUNT(*) FILTER(WHERE "isActive")::int active,COUNT(*) FILTER(WHERE NOT "isActive")::int inactive,(SELECT COUNT(*)::int FROM "SyncRun") "syncRunCount",(SELECT COUNT(*)::int FROM (SELECT "externalId" FROM "Product" WHERE "externalId" IS NOT NULL GROUP BY "externalId" HAVING COUNT(*)>1)d) "duplicateExternalId",md5(COALESCE(string_agg(row_to_json(p)::text,'' ORDER BY p.id),'')) fingerprint FROM "Product" p`))[0] as State
async function protectedSkus(){const [reconText,auditText]=await Promise.all([readFile('second-reconciliation-intermediate.json','utf8'),readFile('final-remaining-xml-audit.json','utf8')]),r=JSON.parse(reconText),a=JSON.parse(auditText);return new Set<string>([...r.knownDeferred.ambiguous,...r.knownDeferred.caseReview,r.knownDeferred.manual.xmlSku,...r.knownDeferred.rejected.map((x:string[])=>x[1]),...a.hiddenDuplicates.rows.map((x:any)=>x.xmlSku),...a.manualDeferred.rows.map((x:any)=>x.xmlSku),...a.existingCandidates.rows.filter((x:any)=>x.detail==='MANUAL_REVIEW').map((x:any)=>x.xmlSku)])}
async function main(){const apply=process.argv.includes('--apply'),allowPath=arg('--allowlist'),xmlPath=arg('--file'),backup=arg('--backup-branch');if(!allowPath||!xmlPath)throw new Error('EXPLICIT_ALLOWLIST_AND_XML_REQUIRED');if(apply&&!backup)throw new Error('FINAL_EXISTING_BACKFILL_BLOCKED_BY_BACKUP');const {prisma}=await import('../lib/prisma');try{const [content,xml,protectedScope]=await Promise.all([readFile(allowPath),readFile(xmlPath,'utf8'),protectedSkus()]),a=parseAllowlist(content,FINAL_EXISTING_ALLOWLIST_SHA),before=await state(prisma);assertBaseline(before);const products=await prisma.product.findMany({select}) as ProductIdentity[];validateScope(a,xml,products,protectedScope);let updated=0;if(apply)updated=await prisma.$transaction(async tx=>{assertBaseline(await state(tx));const locked=await tx.product.findMany({select}) as ProductIdentity[];validateScope(a,xml,locked,protectedScope);const n=await tx.$executeRawUnsafe(`UPDATE "Product" p SET "externalId"=v.external_id FROM (SELECT * FROM unnest($1::text[],$2::text[]) x(id,external_id)) v WHERE p.id=v.id AND p."externalId" IS NULL AND p."isDeleted"=false`,a.entries.map(e=>e.productId),a.entries.map(e=>e.externalIdToSet));if(n!==a.entries.length)throw new Error(`FINAL_EXISTING_AFFECTED_ROWS:${n}`);return n},{isolationLevel:'Serializable',timeout:120000,maxWait:10000});const after=await state(prisma);if(!apply&&JSON.stringify(before)!==JSON.stringify(after))throw new Error('FINAL_EXISTING_DRY_RUN_CHANGED_DATABASE');console.log(JSON.stringify({event:'final_existing_backfill',mode:apply?'apply':'dry-run',allowlistSha256:FINAL_EXISTING_ALLOWLIST_SHA,backupBranch:backup??null,candidates:a.entries.length,wouldUpdate:apply?0:a.entries.length,conflicts:0,skipped:0,updated,databaseWrites:updated,before,after},null,2))}finally{await prisma.$disconnect()}}
main().catch(e=>{console.error(e);process.exitCode=1})
