/* eslint-disable @typescript-eslint/no-explicit-any */
import { config } from 'dotenv';config({path:'.env.local'})
import { readFile } from 'node:fs/promises'
import type { Prisma } from '../generated/prisma/client'
import { getErpExtraData } from '../lib/sync/erp-extra-data-store'
import { SECOND_IMPORT_COUNT,SECOND_IMPORT_EXPECTED_POST,SECOND_IMPORT_XML_SHA,assertSecondImportBaseline,parseSecondImportAllowlist,prepareSecondImportPlan,sha256 } from '../lib/sync/second-new-product-import'
const arg=(name:string)=>{const i=process.argv.indexOf(name);return i<0?undefined:process.argv[i+1]}
async function main(){const execute=process.argv.includes('--execute'),allowPath=arg('--allowlist'),xmlPath=arg('--file'),backup=arg('--backup-branch');if(!allowPath||!xmlPath)throw new Error('Explicit --allowlist and --file are required');if(execute&&!backup)throw new Error('SECOND_NEW_PRODUCT_IMPORT_BLOCKED_BY_BACKUP')
  const {prisma}=await import('../lib/prisma'),state=async(db:any=prisma)=>(await db.$queryRawUnsafe(`SELECT COUNT(*)::int "productCount",COUNT("externalId")::int "externalIdCount",COUNT(*) FILTER(WHERE "externalId" IS NULL)::int "unlinkedCount",COUNT(*) FILTER(WHERE "isActive")::int active,COUNT(*) FILTER(WHERE NOT "isActive")::int inactive,(SELECT COUNT(*)::int FROM "SyncRun") "syncRunCount",md5(COALESCE(string_agg(row_to_json(p)::text,'' ORDER BY p.id),'')) fingerprint FROM "Product" p`))[0] as Record<string,unknown>
  try{const [content,xml]=await Promise.all([readFile(allowPath),readFile(xmlPath,'utf8')]);if(sha256(xml)!==SECOND_IMPORT_XML_SHA)throw new Error('SECOND_NEW_PRODUCT_IMPORT_XML_SHA_MISMATCH');const allowlist=parseSecondImportAllowlist(content),before=await state(),existing=await prisma.product.findMany({select:{id:true,externalId:true,sku:true,barcode:true}}),plan=prepareSecondImportPlan(allowlist,existing)
    if(!execute){const initial=plan.insertable.length===SECOND_IMPORT_COUNT&&plan.metrics.alreadyImported===0,idempotent=plan.insertable.length===0&&plan.metrics.alreadyImported===SECOND_IMPORT_COUNT;if(plan.metrics.conflicts||(!initial&&!idempotent))throw new Error(`SECOND_NEW_PRODUCT_IMPORT_CONFLICTS:${JSON.stringify(plan.metrics)}`);if(initial)assertSecondImportBaseline(before);else for(const [k,v] of Object.entries(SECOND_IMPORT_EXPECTED_POST))if(before[k]!==v)throw new Error(`SECOND_NEW_PRODUCT_IMPORT_IDEMPOTENCY_STATE_DRIFT:${JSON.stringify(before)}`);const after=await state();if(JSON.stringify(before)!==JSON.stringify(after))throw new Error('SECOND_NEW_PRODUCT_IMPORT_DRY_RUN_CHANGED_DATABASE');console.log(JSON.stringify({event:'second_new_product_import_dry_run',...plan.metrics,before,after,backupBranch:null},null,2));return}
    assertSecondImportBaseline(before);if(plan.metrics.conflicts||plan.insertable.length!==SECOND_IMPORT_COUNT)throw new Error(`SECOND_NEW_PRODUCT_IMPORT_FAIL_CLOSED:${JSON.stringify(plan.metrics)}`)
    const startedAt=new Date(),runId=crypto.randomUUID(),currentExtra=await getErpExtraData(prisma),inserted=await prisma.$transaction(async tx=>{assertSecondImportBaseline(await state(tx));const locked=await tx.product.findMany({select:{id:true,externalId:true,sku:true,barcode:true}}),lockedPlan=prepareSecondImportPlan(allowlist,locked);if(lockedPlan.metrics.conflicts||lockedPlan.insertable.length!==SECOND_IMPORT_COUNT)throw new Error('SECOND_NEW_PRODUCT_IMPORT_LOCKED_SCOPE_MISMATCH');let count=0;for(let i=0;i<lockedPlan.insertable.length;i+=250){const batch=lockedPlan.insertable.slice(i,i+250),result=await tx.product.createMany({data:batch.map(e=>({id:e.plannedProductId,externalId:e.externalId,sku:e.sku,barcode:e.barcode,title:e.productTitle,titleEn:null,titleLv:null,description:null,brand:e.brand,category:e.category,price:e.price2,stock:0,image:null,images:[],badges:[],relatedProductIds:[],oftenBoughtTogether:[],certificates:[],compatibleEquipment:[],isActive:false,isDeleted:false,isCustom:false,lastSyncRunId:runId}))});count+=result.count}if(count!==SECOND_IMPORT_COUNT)throw new Error(`SECOND_NEW_PRODUCT_IMPORT_INSERT_COUNT:${count}`);const extra={...currentExtra};for(const e of lockedPlan.insertable)extra[e.externalId]={prices:Object.fromEntries(Object.entries(e.prices).map(([k,v])=>[k,Number(v)])) as any,warehouseQuantities:e.warehouseQuantities};await tx.keyValueSetting.upsert({where:{key:'erp-extra-data'},create:{key:'erp-extra-data',value:extra as unknown as Prisma.InputJsonValue},update:{value:extra as unknown as Prisma.InputJsonValue}});await tx.syncRun.create({data:{id:runId,status:'completed',triggeredBy:`controlled-second-new-product-import:${SECOND_IMPORT_XML_SHA}:${sha256(content)}`,startedAt,finishedAt:new Date(),productsTotal:SECOND_IMPORT_COUNT,productsSynced:count,deactivated:0,errorCount:0}});return count},{isolationLevel:'Serializable',timeout:300_000,maxWait:10_000});console.log(JSON.stringify({event:'second_new_product_import_complete',runId,inserted,backupBranch:backup,durationMs:Date.now()-startedAt.getTime()},null,2))
  }finally{await prisma.$disconnect()}}
main().catch(e=>{console.error(e);process.exitCode=1})
