/* eslint-disable @typescript-eslint/no-explicit-any */
import { createHash } from 'node:crypto'
import { readFile, writeFile } from 'node:fs/promises'
import { config } from 'dotenv'
import { XMLParser } from 'fast-xml-parser'
import { GRINS_WAREHOUSE_INDEX_TO_ID } from '../lib/sync/grins-warehouse-map'
import { allowedStock, clean, csv, excludedStock, numeric } from '../lib/sync/final-remaining-audit'

config({ path: '.env.local' })
const XML_SHA='26c001368c79f9cfb9100d1cf67c0a0c479fe181f11e0b15c5944888f6517cad'
const EXPECTED={productCount:18544,externalIdCount:15754,unlinkedCount:2790,active:2229,inactive:16315,syncRunCount:12,duplicateExternalId:0,fingerprint:'54d1d85a3b11955dcac193b173366fa1'}
type Category='ALREADY_LINKED'|'SAFE_EXISTING_PRODUCT_CANDIDATE'|'MANUAL_EXISTING_PRODUCT_CANDIDATE'|'POSSIBLE_HIDDEN_DUPLICATE'|'MANUAL_OR_DEFERRED'|'REJECTED_MATCH'|'UNRESOLVED_NEW_PRODUCT'
type Raw={sku?:string;code?:string;title?:string;price1?:string;price2?:string;price3?:string;price4?:string;warehouses?:{warehouse?:Array<{'@_id':string;'#text'?:string}>}}
const state=async(p:any)=>(await p.$queryRawUnsafe(`SELECT COUNT(*)::int "productCount",COUNT("externalId")::int "externalIdCount",COUNT(*) FILTER(WHERE "externalId" IS NULL)::int "unlinkedCount",COUNT(*) FILTER(WHERE "isActive")::int active,COUNT(*) FILTER(WHERE NOT "isActive")::int inactive,(SELECT COUNT(*)::int FROM "SyncRun") "syncRunCount",(SELECT COUNT(*)::int FROM(SELECT "externalId" FROM "Product" WHERE "externalId" IS NOT NULL GROUP BY "externalId" HAVING COUNT(*)>1)d) "duplicateExternalId",md5(COALESCE(string_agg(row_to_json(p)::text,'' ORDER BY p.id),'')) fingerprint FROM "Product" p`))[0]
async function main(){
 const {prisma}=await import('../lib/prisma')
 try{
  const before=await state(prisma);for(const[k,v]of Object.entries(EXPECTED))if(before[k]!==v)throw new Error(`BASELINE_GATE_FAILED:${k}`)
  const [freshText,historicalText,xmlText]=await Promise.all([readFile('final-remaining-xml-audit.json','utf8'),readFile('second-reconciliation-intermediate.json','utf8'),readFile('export.xml','utf8')])
  const fresh=JSON.parse(freshText),historical=JSON.parse(historicalText),xmlSha=createHash('sha256').update(xmlText).digest('hex')
  const raw=((new XMLParser({ignoreAttributes:false,attributeNamePrefix:'@_',parseTagValue:false,processEntities:false,isArray:n=>n==='item'||n==='warehouse'}).parse(xmlText)as any).root?.item??[])as Raw[]
  const xml=raw.map(x=>{const warehouses:Record<string,number>={};for(const w of x.warehouses?.warehouse??[]){const id=GRINS_WAREHOUSE_INDEX_TO_ID[Number(w['@_id'])-1];if(id)warehouses[id]=numeric(w['#text'])}return{xmlSku:clean(x.sku),ean:clean(x.code),name:clean(x.title),price1:numeric(x.price1),price2:numeric(x.price2),price3:numeric(x.price3),price4:numeric(x.price4),warehouses,allowedStock:allowedStock(warehouses),excludedStock:excludedStock(warehouses)}})
  if(xmlSha!==XML_SHA||xml.length!==16176||new Set(xml.map(x=>x.xmlSku)).size!==16176)throw new Error('XML_GATE_FAILED')
  const products=await prisma.product.findMany({select:{id:true,externalId:true,sku:true,barcode:true,title:true,brand:true,category:true,images:true,description:true,price:true,stock:true,isActive:true,isDeleted:true,lastSyncRunId:true}})
  const linked=new Set(products.filter(p=>p.externalId).map(p=>p.externalId as string));const unlinked=products.filter(p=>!p.externalId)
  const detailRows=[...fresh.existingCandidates.rows,...fresh.hiddenDuplicates.rows,...fresh.manualDeferred.rows,...fresh.newProductCandidates.rows];const details=new Map(detailRows.map((r:any)=>[String(r.xmlSku),r]))
  const rejected=new Set<string>(historical.knownDeferred.rejected.map((x:[string,string])=>x[1]));const protectedManual=new Set<string>([...historical.knownDeferred.ambiguous,...historical.knownDeferred.caseReview,historical.knownDeferred.manual.xmlSku]);const historicalHidden=new Set<string>(historical.remainingXml.filter((r:any)=>r.classification==='POSSIBLE_HIDDEN_DUPLICATE').map((r:any)=>r.xmlSku))
  const classify=(sku:string):Category=>{if(linked.has(sku))return'ALREADY_LINKED';if(rejected.has(sku))return'REJECTED_MATCH';if(protectedManual.has(sku))return'MANUAL_OR_DEFERRED';if(historicalHidden.has(sku))return'POSSIBLE_HIDDEN_DUPLICATE';const d:any=details.get(sku);if(d?.category==='EXISTING_PRODUCT_CANDIDATE')return d.detail==='SAFE_FUTURE_BACKFILL'?'SAFE_EXISTING_PRODUCT_CANDIDATE':'MANUAL_EXISTING_PRODUCT_CANDIDATE';if(d?.category==='POSSIBLE_HIDDEN_DUPLICATE')return'POSSIBLE_HIDDEN_DUPLICATE';if(d?.category==='MANUAL_OR_DEFERRED')return'MANUAL_OR_DEFERRED';return'UNRESOLVED_NEW_PRODUCT'}
  const history=(sku:string)=>rejected.has(sku)?'historical rejected identity':protectedManual.has(sku)?'historical protected/manual/deferred':historicalHidden.has(sku)?'historical possible hidden duplicate':''
  const action=(c:Category)=>c==='SAFE_EXISTING_PRODUCT_CANDIDATE'?'candidate for future manual backfill':c==='REJECTED_MATCH'?'keep rejected':c==='UNRESOLVED_NEW_PRODUCT'?'candidate for future manual new-product import':'human identity review'
  const classified=xml.map(x=>{const d:any=details.get(x.xmlSku)??{};const category=classify(x.xmlSku);const{warehouses,...base}=x;return{...base,warehouseSnapshot:JSON.stringify(warehouses),category,previousHistory:history(x.xmlSku),reason:history(x.xmlSku)||d.evidence||'No approved automatic identity/import evidence remains',recommendedAction:action(category),exactOrNormalizedClaimant:d.productId??'',claimantSku:d.productSku??'',claimantBarcode:d.productBarcode??'',claimantTitle:d.productTitle??'',claimantActive:d.productActive??'',claimantDeleted:d.productDeleted??'',brandEvidence:d.productBrand??'',volumeEvidence:d.productVolume??'',variantEvidence:d.productType??''}})
  const counts=Object.fromEntries((['ALREADY_LINKED','SAFE_EXISTING_PRODUCT_CANDIDATE','MANUAL_EXISTING_PRODUCT_CANDIDATE','POSSIBLE_HIDDEN_DUPLICATE','MANUAL_OR_DEFERRED','REJECTED_MATCH','UNRESOLVED_NEW_PRODUCT']as Category[]).map(c=>[c,classified.filter(r=>r.category===c).length]));if(Object.values(counts).reduce((a,b)=>a+(b as number),0)!==16176)throw new Error('CLASSIFICATION_TOTAL_FAILED')
  const remaining=classified.filter(r=>r.category!=='ALREADY_LINKED');const localRows=unlinked.map(p=>{const candidates=remaining.filter(r=>r.exactOrNormalizedClaimant===p.id);return{productId:p.id,sku:p.sku??'',barcode:p.barcode??'',title:p.title,brand:p.brand,category:p.category,isActive:p.isActive,isDeleted:p.isDeleted,price:Number(p.price),stock:p.stock,hasSku:Boolean(clean(p.sku)),hasBarcode:Boolean(clean(p.barcode)),xmlCandidateCount:candidates.length,xmlCandidates:candidates.map(r=>r.xmlSku).join('|'),classification:candidates.length?'XML_CANDIDATE':'LOCAL_ONLY',absenceReason:candidates.length?'Identity remains protected/ambiguous or requires manual backfill':'No reasonable XML identity candidate',lastSyncRunId:p.lastSyncRunId??''}})
  const distribution={price2Positive:remaining.filter(r=>r.price2>0).length,price2Zero:remaining.filter(r=>r.price2===0).length,allowedStockPositive:remaining.filter(r=>r.allowedStock>0).length,allowedStockZero:remaining.filter(r=>r.allowedStock===0).length,eanPresent:remaining.filter(r=>r.ean).length,eanAbsent:remaining.filter(r=>!r.ean).length,activeExistingEvidence:remaining.filter(r=>r.claimantActive===true).length,noActiveExistingEvidence:remaining.filter(r=>r.claimantActive!==true).length}
  const importRunIds=['0e9c0e45-f1bf-4105-8590-b1d64d71cf6a','d1718faf-9dad-4d49-a7ca-36576e16a6c4','84a013ab-8246-432f-803a-c5155167724e'];const runs=await prisma.syncRun.findMany({where:{id:{in:importRunIds}},select:{id:true,triggeredBy:true,status:true,productsTotal:true,productsSynced:true},orderBy:{startedAt:'asc'}});if(runs.length!==3)throw new Error('IMPORT_RUN_HISTORY_INCOMPLETE');const waves=[];for(const run of runs){const rows=products.filter(p=>p.lastSyncRunId===run.id);waves.push({...run,currentProducts:rows.length,active:rows.filter(p=>p.isActive).length,inactive:rows.filter(p=>!p.isActive).length})}
  const after=await state(prisma);if(JSON.stringify(before)!==JSON.stringify(after))throw new Error('DATABASE_CHANGED')
  const report={generatedAt:new Date().toISOString(),readOnly:true,databaseWrites:0,xml:{records:xml.length,uniqueSku:16176,sha256:xmlSha,linked:counts.ALREADY_LINKED,remaining:remaining.length},before,after,unchanged:true,categories:counts,remainingDistribution:distribution,manualReviewRequired:remaining.length,automaticImportScopeRemaining:0,localProducts:{total:unlinked.length,active:unlinked.filter(p=>p.isActive).length,inactive:unlinked.filter(p=>!p.isActive).length,withSku:unlinked.filter(p=>clean(p.sku)).length,withoutSku:unlinked.filter(p=>!clean(p.sku)).length,withBarcode:unlinked.filter(p=>clean(p.barcode)).length,withoutBarcode:unlinked.filter(p=>!clean(p.barcode)).length,softDeleted:unlinked.filter(p=>p.isDeleted).length,xmlCandidate:localRows.filter(r=>r.classification==='XML_CANDIDATE').length,localOnly:localRows.filter(r=>r.classification==='LOCAL_ONLY').length},importWaves:waves,automaticImportsActive:waves.reduce((n,w)=>n+w.active,0),classificationBySku:classified.map(r=>({xmlSku:r.xmlSku,category:r.category}))}
  const categoryTable=Object.entries(counts).map(([k,v])=>`| ${k} | ${v} |`).join('\n');const waveTable=waves.map(w=>`| ${w.id} | ${w.productsTotal} | ${w.currentProducts} | ${w.active} | ${w.inactive} |`).join('\n')
  const md=`# Post-import final reconciliation\n\nGenerated: ${report.generatedAt}. Strictly read-only; database writes: **0**.\n\n## Safety gates\n\n- XML: ${xml.length} records / 16,176 unique SKU; SHA-256 \`${xmlSha}\`.\n- Product/externalId/unlinked: ${before.productCount}/${before.externalIdCount}/${before.unlinkedCount}. Active/inactive: ${before.active}/${before.inactive}. SyncRun: ${before.syncRunCount}. Duplicate externalId: ${before.duplicateExternalId}.\n- Before/after fingerprint: \`${before.fingerprint}\` / \`${after.fingerprint}\` — identical.\n\n## Mutually exclusive XML reconciliation\n\n| Category | Count |\n|---|---:|\n${categoryTable}\n| **TOTAL** | **16176** |\n\nExact remaining scope: **${remaining.length} = 16176 - ${counts.ALREADY_LINKED}**. Historical protected/manual/deferred/rejected/hidden decisions override fresh fuzzy evidence. Product 13324 / XML 97388150 remains protected.\n\n## Remaining distributions\n\n- price2 > 0 / = 0: ${distribution.price2Positive} / ${distribution.price2Zero}\n- allowed stock > 0 / = 0: ${distribution.allowedStockPositive} / ${distribution.allowedStockZero}\n- EAN present / absent: ${distribution.eanPresent} / ${distribution.eanAbsent}\n- active existing-product evidence / none: ${distribution.activeExistingEvidence} / ${distribution.noActiveExistingEvidence}\n\nAll ${remaining.length} remaining rows require review; automatic import scope remaining is **0**. Row-level evidence, warehouse snapshots, history, reasons, and recommended actions are in the CSV.\n\n## Unlinked local Products\n\n${JSON.stringify(report.localProducts)}. LOCAL_ONLY is not an obsolete/deactivation decision. Active unlinked: **${report.localProducts.active}**.\n\n## New-product import waves\n\n| SyncRun | expected | current by lastSyncRunId | active | inactive |\n|---|---:|---:|---:|---:|\n${waveTable}\n\nAll imported rows remain distinguishable by lastSyncRunId; active imported rows: **${report.automaticImportsActive}**.\n`
  await Promise.all([writeFile('post-import-final-reconciliation.json',JSON.stringify(report,null,2)+'\n'),writeFile('post-import-final-reconciliation.md',md),writeFile('remaining-xml-manual-review.csv',csv(remaining)),writeFile('remaining-existing-unlinked.csv',csv(localRows)),writeFile('active-unlinked-products.csv',csv(localRows.filter(r=>r.isActive)))])
  console.log(JSON.stringify({categories:counts,remaining:remaining.length,distribution,localProducts:report.localProducts,waves,automaticImportsActive:report.automaticImportsActive,before,after,databaseWrites:0},null,2))
 }finally{await prisma.$disconnect()}
}
main().catch(e=>{console.error(e);process.exitCode=1})
