/* eslint-disable @typescript-eslint/no-explicit-any */
import { createHash } from 'node:crypto'
import { readFile,writeFile } from 'node:fs/promises'
import { config } from 'dotenv'
import { XMLParser } from 'fast-xml-parser'
import { GRINS_WAREHOUSE_INDEX_TO_ID } from '../lib/sync/grins-warehouse-map'
import { allowedStock,clean,normalizedEan,normalizedName,numeric,quantile,skuKeys } from '../lib/sync/second-new-product-audit'
import { SECOND_IMPORT_BASELINE,SECOND_IMPORT_COUNT,SECOND_IMPORT_XML_SHA,assertSecondImportBaseline,sha256,type SecondImportAllowlist,type SecondImportEntry } from '../lib/sync/second-new-product-import'
config({path:'.env.local'})
type Raw={sku?:string;code?:string;title?:string;price1?:string;price2?:string;price3?:string;price4?:string;warehouses?:{warehouse?:Array<{'@_id':string;'#text'?:string}>}}
const parser=new XMLParser({ignoreAttributes:false,attributeNamePrefix:'@_',parseTagValue:false,processEntities:false,isArray:n=>n==='item'||n==='warehouse'})
const idFor=(sku:string)=>{const h=createHash('sha256').update(`grins-second:${sku}`).digest('hex');return`${h.slice(0,8)}-${h.slice(8,12)}-4${h.slice(13,16)}-a${h.slice(17,20)}-${h.slice(20,32)}`}
const money=(value:number)=>value.toFixed(2)
const index=<T>(rows:T[],key:(row:T)=>string)=>{const out=new Map<string,T[]>();for(const row of rows){const k=key(row);if(k)out.set(k,[...(out.get(k)??[]),row])}return out}
async function main(){const {prisma}=await import('../lib/prisma');const state=async()=>(await prisma.$queryRawUnsafe<any[]>(`SELECT COUNT(*)::int "productCount",COUNT("externalId")::int "externalIdCount",COUNT(*) FILTER(WHERE "externalId" IS NULL)::int "unlinkedCount",COUNT(*) FILTER(WHERE "isActive")::int active,COUNT(*) FILTER(WHERE NOT "isActive")::int inactive,(SELECT COUNT(*)::int FROM "SyncRun") "syncRunCount",md5(COALESCE(string_agg(row_to_json(p)::text,'' ORDER BY p.id),'')) fingerprint FROM "Product" p`))[0]
  try{const before=await state();assertSecondImportBaseline(before)
    const [xmlText,reconText,diagnosticText]=await Promise.all([readFile('export.xml','utf8'),readFile('second-reconciliation-intermediate.json','utf8'),readFile('second-new-product-import-audit.json','utf8')]);if(sha256(xmlText)!==SECOND_IMPORT_XML_SHA)throw new Error('SECOND_NEW_PRODUCT_IMPORT_XML_SHA_MISMATCH')
    const raw=((parser.parse(xmlText) as {root?:{item?:Raw[]}}).root?.item??[]),recon=JSON.parse(reconText),diagnostic=JSON.parse(diagnosticText),newSkus=new Set<string>(recon.remainingXml.filter((r:any)=>r.classification==='NEW_PRODUCT_HIGH_CONFIDENCE').map((r:any)=>r.xmlSku))
    if(raw.length!==16176||new Set(raw.map(x=>clean(x.sku))).size!==16176||newSkus.size!==9972)throw new Error('SECOND_NEW_PRODUCT_IMPORT_RECONSTRUCTION_INPUT_DRIFT')
    const parse=(x:Raw)=>{const warehouses:Record<string,number>={};for(const w of x.warehouses?.warehouse??[]){const id=GRINS_WAREHOUSE_INDEX_TO_ID[Number(w['@_id'])-1];if(id)warehouses[id]=numeric(w['#text'])}return{sku:clean(x.sku),ean:clean(x.code),title:clean(x.title),price1:numeric(x.price1),price2:numeric(x.price2),price2Raw:clean(x.price2),price3:numeric(x.price3),price4:numeric(x.price4),warehouses,stock:allowedStock(warehouses)}}
    const all=raw.map(parse),groupB=all.filter(x=>newSkus.has(x.sku)&&x.price2>0&&x.stock===0);if(groupB.length!==9274)throw new Error('SECOND_NEW_PRODUCT_IMPORT_GROUP_B_DRIFT')
    const prices=groupB.map(x=>x.price2),q1=quantile(prices,.25),q3=quantile(prices,.75),high=q3+3*(q3-q1),products=await prisma.product.findMany({select:{id:true,externalId:true,sku:true,barcode:true,title:true,titleEn:true,titleLv:true}})
    const ext=index(products,p=>clean(p.externalId)),sku=index(products,p=>clean(p.sku)),ean=index(products,p=>normalizedEan(p.barcode)),names=new Map<string,typeof products>(),keys=new Map<string,typeof products>(),xmlEan=index(all,x=>normalizedEan(x.ean));for(const p of products){for(const name of[p.title,p.titleEn,p.titleLv]){const k=normalizedName(name);if(k)names.set(k,[...(names.get(k)??[]),p])}for(const k of skuKeys(p.sku))keys.set(k,[...(keys.get(k)??[]),p])}
    const review:string[]=[],entries:SecondImportEntry[]=[]
    for(const x of groupB){const normalizedClaimants=new Set<string>();for(const k of skuKeys(x.sku))for(const p of keys.get(k)??[])if(clean(p.sku)!==x.sku)normalizedClaimants.add(p.id);const e=normalizedEan(x.ean),hard=ext.has(x.sku)||sku.has(x.sku)||Boolean(e&&(ean.has(e)||(xmlEan.get(e)?.length??0)>1))||normalizedClaimants.size>0||(names.get(normalizedName(x.title))?.length??0)>0,priceReview=x.price2>high||!/^\d+(?:\.\d{1,2})?$/u.test(x.price2Raw)
      if(hard)throw new Error(`SECOND_NEW_PRODUCT_IMPORT_IDENTITY_DRIFT:${x.sku}`);if(priceReview){review.push(x.sku);continue}
      entries.push({plannedProductId:idFor(x.sku),xmlSku:x.sku,externalId:x.sku,sku:x.sku,barcode:x.ean||null,sourceTitle:x.title,productTitle:x.sku,price2:money(x.price2),allowedStock:0,warehouseQuantities:x.warehouses,prices:{price1:money(x.price1),price2:money(x.price2),price3:money(x.price3),price4:money(x.price4)},identityEvidence:['fresh DB+XML reconstruction found no externalId, exact/case/normalized SKU, barcode/EAN, normalized-name, deferred, manual, rejected, or hidden-duplicate conflict','price and stock were not used as identity evidence'],brand:'',category:'uncategorized',titleEn:null,titleLv:null,description:null,imageReferences:[],isActive:false,classification:'SECOND_IMPORT_SAFE_CANDIDATE'})}
    entries.sort((a,b)=>a.xmlSku.localeCompare(b.xmlSku,'en'));review.sort((a,b)=>a.localeCompare(b,'en'));if(entries.length!==SECOND_IMPORT_COUNT||review.length!==429)throw new Error(`SECOND_NEW_PRODUCT_IMPORT_RECONSTRUCTION_DRIFT:${entries.length}:${review.length}`)
    const diagnosticSafe=new Set<string>(diagnostic.safeCandidates.map((x:any)=>x.xmlSku)),reconstructed=new Set(entries.map(x=>x.xmlSku)),disappeared=[...diagnosticSafe].filter(x=>!reconstructed.has(x)),newlyAppeared=[...reconstructed].filter(x=>!diagnosticSafe.has(x));if(disappeared.length||newlyAppeared.length)throw new Error(`SECOND_NEW_PRODUCT_IMPORT_SAFE_SET_DRIFT:${JSON.stringify({disappeared,newlyAppeared})}`)
    const allowlist:SecondImportAllowlist={schemaVersion:1,wave:'second-new-product-import',executable:true,authorizedForApply:true,entryCount:SECOND_IMPORT_COUNT,xmlSha256:SECOND_IMPORT_XML_SHA,baseline:SECOND_IMPORT_BASELINE,reviewExclusionCount:429,reviewExclusionSha256:sha256(review.join('\n')),reviewExcludedSkus:review,entries},text=JSON.stringify(allowlist,null,2)+'\n',allowlistSha=sha256(text)
    const after=await state();if(JSON.stringify(before)!==JSON.stringify(after))throw new Error('SECOND_NEW_PRODUCT_IMPORT_PREPARATION_CHANGED_DATABASE')
    await writeFile('second-new-product-import-allowlist.json',text)
    console.log(JSON.stringify({before,after,databaseWrites:0,reconstruction:{expected:8845,actual:entries.length,disappeared:0,newlyAppeared:0,classificationDrift:0,reviewExcluded:review.length},zeroStock:{trueZero:entries.filter(e=>Object.values(e.warehouseQuantities).every(v=>v===0)).length,excludedWarehouseOnly:entries.filter(e=>Object.entries(e.warehouseQuantities).some(([id,v])=>!['10000','10001','10002','10005'].includes(id)&&v>0)).length},allowlist:{file:'second-new-product-import-allowlist.json',entries:entries.length,sha256:allowlistSha,xmlSha256:SECOND_IMPORT_XML_SHA,baselineFingerprint:SECOND_IMPORT_BASELINE.fingerprint}},null,2))
  }finally{await prisma.$disconnect()}}
main().catch(e=>{console.error(e);process.exitCode=1})
