/* eslint-disable @typescript-eslint/no-explicit-any */
import { config } from 'dotenv';config({path:'.env.local'})
import { readFile } from 'node:fs/promises'
import { getErpExtraData } from '../lib/sync/erp-extra-data-store'
import { SECOND_IMPORT_COUNT,SECOND_IMPORT_EXPECTED_POST,assertSecondImportBaseline,parseSecondImportAllowlist,prepareSecondImportPlan } from '../lib/sync/second-new-product-import'
async function main(){const post=process.argv.includes('--post-import'),{prisma}=await import('../lib/prisma');try{const allowlist=parseSecondImportAllowlist(await readFile('second-new-product-import-allowlist.json')),all=await prisma.product.findMany({select:{id:true,externalId:true,sku:true,barcode:true,title:true,price:true,stock:true,isActive:true,isDeleted:true,brand:true,category:true,lastSyncRunId:true}}),state=(await prisma.$queryRawUnsafe<any[]>(`SELECT COUNT(*)::int "productCount",COUNT("externalId")::int "externalIdCount",COUNT(*) FILTER(WHERE "externalId" IS NULL)::int "unlinkedCount",COUNT(*) FILTER(WHERE "isActive")::int active,COUNT(*) FILTER(WHERE NOT "isActive")::int inactive,(SELECT COUNT(*)::int FROM "SyncRun") "syncRunCount",md5(COALESCE(string_agg(row_to_json(p)::text,'' ORDER BY p.id),'')) fingerprint FROM "Product" p`))[0]
    if(!post){assertSecondImportBaseline(state);const plan=prepareSecondImportPlan(allowlist,all);console.log(JSON.stringify({phase:'pre-import',...plan.metrics,state,databaseWrites:0},null,2));if(plan.insertable.length!==SECOND_IMPORT_COUNT||plan.metrics.conflicts)throw new Error('SECOND_IMPORT_PREFLIGHT_FAILED');return}
    for(const [k,v] of Object.entries(SECOND_IMPORT_EXPECTED_POST))if(state[k]!==v)throw new Error(`SECOND_IMPORT_POST_STATE_MISMATCH:${JSON.stringify(state)}`);const byExternal=new Map(all.filter(p=>p.externalId).map(p=>[p.externalId!,p])),extra=await getErpExtraData(prisma);let correct=0,mismatches=0,erpPriceMismatches=0,erpWarehouseMismatches=0,active=0;const runIds=new Set<string>()
    for(const e of allowlist.entries){const p=byExternal.get(e.externalId);if(p?.isActive)active++;if(p&&p.id===e.plannedProductId&&p.sku===e.sku&&p.barcode===e.barcode&&p.title===e.productTitle&&Number(p.price)===Number(e.price2)&&p.stock===0&&!p.isActive&&!p.isDeleted&&p.brand===e.brand&&p.category===e.category){correct++;if(p.lastSyncRunId)runIds.add(p.lastSyncRunId)}else mismatches++;const x=extra[e.externalId];if(!x||JSON.stringify(x.warehouseQuantities)!==JSON.stringify(e.warehouseQuantities))erpWarehouseMismatches++;if(!x||(['price1','price2','price3','price4'] as const).some(k=>Number(x.prices[k])!==Number(e.prices[k])))erpPriceMismatches++}
    const originalFingerprint=(await prisma.$queryRawUnsafe<any[]>(`SELECT md5(COALESCE(string_agg(row_to_json(p)::text,'' ORDER BY p.id),'')) fingerprint FROM "Product" p WHERE NOT (p.id=ANY($1::text[]))`,allowlist.entries.map(e=>e.plannedProductId)))[0].fingerprint,duplicates=(await prisma.$queryRawUnsafe<any[]>(`SELECT COUNT(*)::int count FROM (SELECT "externalId" FROM "Product" WHERE "externalId" IS NOT NULL GROUP BY "externalId" HAVING COUNT(*)>1)x`))[0].count,run=runIds.size===1?await prisma.syncRun.findUnique({where:{id:[...runIds][0]}}):null,runValid=Boolean(run&&run.status==='completed'&&run.productsTotal===SECOND_IMPORT_COUNT&&run.productsSynced===SECOND_IMPORT_COUNT&&!run.errorCount&&!run.deactivated&&run.triggeredBy.includes('second-new-product-import'))
    const result={phase:'post-import',expected:SECOND_IMPORT_COUNT,correct,mismatches,erpPriceMismatches,erpWarehouseMismatches,active,inactive:SECOND_IMPORT_COUNT-active,duplicateExternalIds:duplicates,originalProductFingerprint:originalFingerprint,originalProductsUnchanged:originalFingerprint===allowlist.baseline.fingerprint,run,runValid,state,databaseWrites:0};console.log(JSON.stringify(result,null,2));if(mismatches||erpPriceMismatches||erpWarehouseMismatches||active||duplicates||originalFingerprint!==allowlist.baseline.fingerprint||!runValid)throw new Error('SECOND_IMPORT_VERIFICATION_FAILED')
  }finally{await prisma.$disconnect()}}
main().catch(e=>{console.error(e);process.exitCode=1})
