/* eslint-disable @typescript-eslint/no-explicit-any */
import { config } from 'dotenv';config({path:'.env.local'})
import { readFile } from 'node:fs/promises'
import { getErpExtraData } from '../lib/sync/erp-extra-data-store'
import { assertImportBaseline, parseImportAllowlist, prepareImportPlan } from '../lib/sync/first-new-product-import'
async function main(){const post=process.argv.includes('--post-import'),{prisma}=await import('../lib/prisma');try{const content=await readFile('first-new-product-import-allowlist.json'),a=parseImportAllowlist(content),all=await prisma.product.findMany({select:{id:true,externalId:true,sku:true,barcode:true,title:true,price:true,stock:true,isActive:true,isDeleted:true,brand:true,category:true,lastSyncRunId:true}})
  const state=(await prisma.$queryRawUnsafe<any[]>(`SELECT COUNT(*)::int "productCount",COUNT("externalId")::int "externalIdCount",COUNT(*) FILTER(WHERE "externalId" IS NULL)::int "unlinkedCount",COUNT(*) FILTER(WHERE "isActive")::int active,COUNT(*) FILTER(WHERE NOT "isActive")::int inactive,(SELECT COUNT(*)::int FROM "SyncRun") "syncRunCount",md5(COALESCE(string_agg(row_to_json(p)::text,'' ORDER BY p.id),'')) fingerprint FROM "Product" p`))[0]
  if(!post){assertImportBaseline(state);const plan=prepareImportPlan(a,all);console.log(JSON.stringify({phase:'pre-import',...plan.metrics,state,databaseWrites:0},null,2));return}
  const byExternal=new Map(all.filter(p=>p.externalId).map(p=>[p.externalId!,p])),extra=await getErpExtraData(prisma);let correct=0,mismatches=0,erpMismatches=0,erpPriceMismatches=0,newActive=0;const runIds=new Set<string>()
  for(const e of a.entries){const p=byExternal.get(e.externalId);if(p?.isActive)newActive++;if(p&&p.id===e.plannedProductId&&p.sku===e.xmlSku&&p.barcode===e.barcode&&p.title===e.productTitle&&Number(p.price)===Number(e.price2)&&p.stock===e.allowedStock&&!p.isActive&&!p.isDeleted&&p.brand===e.brand&&p.category===e.category){correct++;if(p.lastSyncRunId)runIds.add(p.lastSyncRunId)}else mismatches++;const x=extra[e.externalId];if(!x||JSON.stringify(x.warehouseQuantities)!==JSON.stringify(e.warehouseQuantities))erpMismatches++;if(!x||(['price1','price2','price3','price4'] as const).some(k=>Number(x.prices[k])!==Number(e.prices[k])))erpPriceMismatches++}
  const originalFingerprint=(await prisma.$queryRawUnsafe<any[]>(`SELECT md5(COALESCE(string_agg(row_to_json(p)::text,'' ORDER BY p.id),'')) fingerprint FROM "Product" p WHERE NOT (p.id=ANY($1::text[]))`,a.entries.map(e=>e.plannedProductId)))[0].fingerprint
  const [duplicates,run]=await Promise.all([prisma.$queryRawUnsafe<any[]>(`SELECT (SELECT COUNT(*)::int FROM (SELECT "externalId" FROM "Product" WHERE "externalId" IS NOT NULL GROUP BY "externalId" HAVING COUNT(*)>1)x) "duplicateExternalIds",(SELECT COUNT(*)::int FROM (SELECT sku FROM "Product" WHERE sku IS NOT NULL GROUP BY sku HAVING COUNT(*)>1)x) "duplicateSkus",(SELECT COUNT(*)::int FROM (SELECT barcode FROM "Product" WHERE barcode IS NOT NULL GROUP BY barcode HAVING COUNT(*)>1)x) "duplicateBarcodes"`),runIds.size===1?prisma.syncRun.findUnique({where:{id:[...runIds][0]}}):null])
  const runValid=Boolean(run&&run.status==='completed'&&run.productsTotal===a.entries.length&&run.productsSynced===a.entries.length&&run.errorCount===0&&run.deactivated===0&&run.triggeredBy.includes('controlled-first-new-product-import'))
  const result={phase:'post-import',expected:a.entries.length,correct,mismatches,erpMismatches,erpPriceMismatches,newActive,newInactive:a.entries.length-newActive,originalProductFingerprint:originalFingerprint,originalProductsUnchanged:originalFingerprint===a.baseline.fingerprint,runIds:[...runIds],run,runValid,duplicates:duplicates[0],state,databaseWrites:0};console.log(JSON.stringify(result,null,2));if(mismatches||erpMismatches||erpPriceMismatches||newActive||originalFingerprint!==a.baseline.fingerprint||runIds.size!==1||!runValid||duplicates[0].duplicateExternalIds)throw new Error('FIRST_IMPORT_VERIFICATION_FAILED')
}finally{await prisma.$disconnect()}}main().catch(e=>{console.error(e);process.exitCode=1})
