import { config } from 'dotenv';config({path:'.env.local'})
import { readFile } from 'node:fs/promises'
import { parseGrinsXml } from '../lib/sync/grins-xml-parser'
import { getErpExtraData } from '../lib/sync/erp-extra-data-store'
import { selectedStock } from '../lib/sync/sync-rules'
import { FOURTH_WAVE_MANUAL_IDS, FOURTH_WAVE_REJECTED_IDS, FOURTH_WAVE_DEFERRED_SKUS, FOURTH_WAVE_SIZE, validateFourthWave } from '../lib/sync/fourth-wave-backfill'

async function main(){const postBackfill=process.argv.includes('--post-backfill'),postSync=process.argv.includes('--post-sync'),phase=postSync?'post-sync':postBackfill?'post-backfill':'pre-apply-readiness';const{prisma}=await import('../lib/prisma');try{const[content,xml]=await Promise.all([readFile('fourth-wave-ean-allowlist.json'),readFile('export.xml','utf8')]),all=await prisma.product.findMany({select:{id:true,sku:true,externalId:true,barcode:true,isDeleted:true}}),allowlist=validateFourthWave(content,xml,all,postBackfill||postSync?'post-backfill':'pre-backfill'),ids=allowlist.entries.map(x=>x.productId),feedById=new Map(parseGrinsXml(xml).map(item=>[item.externalId,item])),products=await prisma.product.findMany({where:{id:{in:ids}},select:{id:true,externalId:true,sku:true,barcode:true,price:true,stock:true,isActive:true,isDeleted:true,title:true,brand:true,category:true,description:true,technicalSpecs:true,image:true,images:true,createdAt:true}}),excluded=await prisma.product.findMany({where:{id:{in:[...FOURTH_WAVE_MANUAL_IDS,...FOURTH_WAVE_REJECTED_IDS]}},select:{id:true,externalId:true}}),deferred=await prisma.product.findMany({where:{OR:[{externalId:{in:[...FOURTH_WAVE_DEFERRED_SKUS]}},{sku:{in:[...FOURTH_WAVE_DEFERRED_SKUS]}}]},select:{id:true,externalId:true,sku:true}}),duplicates=await prisma.$queryRawUnsafe<Array<{externalId:string;count:number}>>(`SELECT "externalId",COUNT(*)::int count FROM "Product" WHERE "externalId" IS NOT NULL GROUP BY "externalId" HAVING COUNT(*)>1`),extra=postSync?await getErpExtraData(prisma):{}
  let identityMismatches=0,protectedFieldMismatches=0,priceMismatches=0,stockMismatches=0,erpTierMismatches=0,warehouseSnapshotMismatches=0
  const byId=new Map(products.map(product=>[product.id,product]));for(const entry of allowlist.entries){const product=byId.get(entry.productId),item=feedById.get(entry.externalIdToSet);if(!product||!item||product.sku?.trim()||product.barcode!==entry.productBarcode||product.externalId!==(postBackfill||postSync?entry.externalIdToSet:null)){identityMismatches++;continue}const expected=entry.protectedProductBaseline,actual={isActive:product.isActive,title:product.title,brand:product.brand,category:product.category,description:product.description??'',technicalSpecs:product.technicalSpecs??null,image:product.image??'',imageCount:product.images.length,createdAt:product.createdAt.toISOString()};if(JSON.stringify(actual)!==JSON.stringify(expected))protectedFieldMismatches++;if(postSync){if(item.price>0&&Number(product.price)!==item.price)priceMismatches++;if(product.stock!==selectedStock(item.warehouseQuantities??{}))stockMismatches++;const stored=extra[entry.externalIdToSet];if(!stored||JSON.stringify(stored.prices)!==JSON.stringify(item.prices))erpTierMismatches++;if(!stored||JSON.stringify(stored.warehouseQuantities)!==JSON.stringify(item.warehouseQuantities))warehouseSnapshotMismatches++}}
  const deferredIntersection=allowlist.entries.filter(entry=>FOURTH_WAVE_DEFERRED_SKUS.has(entry.externalIdToSet.toLocaleUpperCase('en-US'))).length
  const result={phase,scope:products.length,identityMismatches,protectedFieldMismatches,productSkuStillEmpty:products.filter(p=>!p.sku?.trim()).length,barcodeUnchanged:products.filter(p=>p.barcode===allowlist.entries.find(e=>e.productId===p.id)?.productBarcode).length,duplicateExternalIds:duplicates.length,manualRejectedAssigned:excluded.filter(p=>p.externalId!==null).length,deferredRecordsObserved:deferred.length,deferredIntersection,priceMismatches,stockMismatches,erpTierMismatches,warehouseSnapshotMismatches,note:postSync?'Post-sync field checks executed':'Post-apply results are intentionally not claimed before apply'};console.log(JSON.stringify(result,null,2));if(products.length!==FOURTH_WAVE_SIZE||identityMismatches||protectedFieldMismatches||duplicates.length||excluded.some(p=>p.externalId!==null)||deferredIntersection||(postSync&&(priceMismatches||stockMismatches||erpTierMismatches||warehouseSnapshotMismatches)))throw new Error('FOURTH_WAVE_VERIFICATION_FAILED')
}finally{await prisma.$disconnect()}}
main().catch(error=>{console.error(error);process.exitCode=1})
